### ISSUE TITLE
Analyzer for FailedMount Pod Events

### ISSUE THREAD

**Issue by CpuID** [replicatedhq/troubleshoot#1009]
**Describe the rationale for the suggested feature.**

Catching scenarios where Rook (or other storage backends) cannot mount a volume that's backing a PV/PVC.

**Describe the feature**

We should analyze all Pod events for `Reason` -> `FailedMount`.

**Describe alternatives you've considered**

N/A

**Comment by diamonwiggins** [comment]
FYI https://github.com/replicatedhq/troubleshoot/issues/911 in case you think there's some overlap and want to develop some of these ideas on that one.

**Comment by CpuID** [comment]
@diamonwiggins I'll keep both open for now, but I do agree there's definitely overlap.

It feels like this issue would depend on #911 being completed first, then this might just end up being an addition to our default specs once `eventsAnalyze` was available 👍
