### ISSUE TITLE
Expose rendered spec after merging via an API and the cli

### ISSUE THREAD

**Issue by banjoh** [replicatedhq/troubleshoot#1024]
**Describe the rationale for the suggested feature.**

Troubleshoot has the ability to [merge multiple specs](https://troubleshoot.sh/docs/support-bundle/collecting/#collect-a-support-bundle-using-multiple-specs) and run all collectors/analysers/redactors in the resulting spec. These specs can be pulled from (as of today) the following sources
- http(s) urls
- oci uris
- files on disk (will include [multidocs as well](https://github.com/replicatedhq/troubleshoot/issues/1023))
- [embedded uris](https://troubleshoot.sh/docs/support-bundle/supportbundle/#uri)

Merged collectors are then [deduplicated](https://github.com/replicatedhq/troubleshoot/pull/972) and some default specs (cluster-resources, cluster-info, default redactors) added as well. It has now become hard to get a full picture of how the full support bundle spec would look like before executing it.

**Describe the feature**

- Define a public API that would be used to build a full spec from merged specs
- Using this public API, add a new subcommand/cli option to render the entire spec. Some examples of how the CLI interface would look like are
```sh
support-bundle render-spec <uris...> # same for preflight
support-bundle <uris...> --dry-run # same for preflight
```

**Tasks**
- [x] Add flag to `preflight` binary
- [ ] Add flag to `support-bundle` binary

**Comment by chris-sanders** [comment]
I really like this idea. Removing confusion can pay off in multiple ways.
