### ISSUE TITLE
Should we add a built in prometheus collector and analyzer functionality?

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/troubleshoot#104]

**Comment by matias-manavella-nimble** [comment]
@marccampbell Hi Marc, what do you specifically have in mind for this functionality? Is the Idea hitting the prom servers endpoint in the cluster to get the time-series data and save it in the bundle?  Do you want to include the possibility to analyze the data(e.g, allowing the user to set alarm triggers)?

This, together with using a logging tool such as Fluentd to get, for example, kubelet logs as stated in issue #226 (or any other kind of logs) would be great enhacements, adding logging and monitoring capability. 

If you agree I could start working on this two points, just let me know!

**Comment by xavpaice** [comment]
I think it's time to close this as not planned.  The issue has been discussed several times, and we came to the conclusion that the business value of adding this collector does not match the effort required.  There's limitations to which environments it's useful in.

Long term it would be good to collect all the kubelet logs, performance info, etc in a host collector.
