### ISSUE TITLE
Capture Endpoints in Support Bundles (for Services etc)

### ISSUE THREAD

**Issue by CpuID** [replicatedhq/troubleshoot#1046]
**Describe the rationale for the suggested feature.**

So we can diagnose the state of service <-> pod relationships using `sbctl`.

**Describe the feature**

Right now we capture pod data, and service data, but not endpoints? Add those in also...

**Describe alternatives you've considered**

Asking the customer for `kubectl get ep -A`.

**Additional context**

N/A

**Comment by chris-sanders** [comment]
This seems like a great addition, and it's something and end user isn't typically going to understand so trying to get the information from the user directly is likely problematic.
