### ISSUE TITLE
Bundle default specs in binary

### ISSUE THREAD

**Issue by banjoh** [replicatedhq/troubleshoot#1053]
**Describe the rationale for the suggested feature.**

When troubleshooting, users occasionally have to run commands such as below. This makes troubleshooting easier when a user does not have a ready made spec to use. They can use this contributed spec. Without one, crafting a spec is tasking if a user finds themselves trying to do this when troubleshooting an incident.

```sh
kubectl support-bundle https://raw.githubusercontent.com/replicatedhq/troubleshoot-specs/main/in-cluster/default-kurl.yaml https://raw.githubusercontent.com/replicatedhq/troubleshoot-specs/main/host/cluster-down.yaml
```

It gets trickier in airgapped environments. Users have to download these specs and copy them into the airgap environment.

We propose bundling default specs in the binary which will ensure the `support-bundle` binary comes "batteries included". The specs to be used are https://github.com/replicatedhq/troubleshoot-specs

**Describe the feature**

Add commands the following new `support-bundle` commands. (_Command names subject to change_)

```sh
support-bundle list-bundled-specs | list-named-specs (naming is hard!!)
support-bundle show-bundled-spec <bundled-spec-name> # shows what would be run
support-bundle <bundled-spec-name> # collects support bundle with bundled spec
```

The bundled spec will have a URI field pointing to original spec. This ensures updates are applied whenever the source spec changes.

**Describe alternatives you've considered**

An alternative, which will probably still be considered, is utilising a registry of specs. This way discoverability is easier.

**Additional context**
- Perhaps `support-bundle show-bundled-spec <bundled-spec-name>` may not be needed cause since we will have https://github.com/replicatedhq/troubleshoot/issues/1024. But there may be cases where we need to show the pre-merged spec.
- The specs might end up being opinionated to kurl clusters, kotsadm clusters etc. I don't this this is a problem but highlighting it nonetheless. How we name them will probably be helpful in communicating this.

**Comment by xavpaice** [comment]
for the in-cluster spec, I'd prefer if we can just use the tools to search for specs with an appropriate label.  In prior versions we can use a named secret for this, too.

For cluster-down type specs, agree it would be nice to have something which collects a reasonable set of defaults.  We do still rely on folks to download and transfer the most recent Troubleshoot binary, unless the one installed by kURL is new enough to include the recent features/bug fixes.

**Comment by chris-sanders** [comment]
This would be a rethinking of https://github.com/replicatedhq/troubleshoot/blob/main/docs/design/design-principles.md#tools-not-specs

I'm concerned any 'built in' spec would become a burden and UX complication. Does a users input add to the default, override the default, what if they just want to redact part of the default, etc.

It's for that reason I'm personally more inclined to have a well defined place to look for specs. But we should discuss in a community meeting or otherwise if you think there's still room for a default and the UX issue is something we can clearly define ahead of time.

**Comment by banjoh** [comment]
Given comments above, I'm going to close this out in favour thinking of how we can discover specs with ease.
