### ISSUE TITLE
Add linux/arm release

### ISSUE THREAD

**Issue by juanluisvaladas** [replicatedhq/troubleshoot#1069]
**Describe the rationale for the suggested feature.**

At k0s we support amd64, arm64 and arm and we need support-bundle into all our architectures, therefore we would like to have official releases for every architecture.

Currently we can compile it into arm without further changes by just changing the GOARCH and we haven't found any issue so far.

**Describe the feature**

Release binaries for linux/arm just like it's done already for linux/arm64 and linux/amd64.

**Describe alternatives you've considered**

We can build support bundle ourselves: https://github.com/k0sproject/k0s/pull/2902/files#diff-824296bdf39d6c59a3131a8c15d0031a1274bc0243c37a0941f48b6353e13cd8

This is not a blocker for us, we're asking for this because we think that:
1-  Releasing arm support-bundle in its own repo makes sense not just for us but for the project itself.
2- We've had a look at the build-test-deploy.yaml workflow and at goreleaser and we think this change wouldn't be very difficult or large. Also we don't think this will add a significant amount of maintenance in the long run.

We can make the PR for these changes ourselves if you agree that it makes sense.

**Comment by CpuID** [comment]
Hi @juanluisvaladas

That seems fine IMO, adding an extra architecture isn't a massive penalty if it adds hardware flexibility.

I'm curious - what hardware platforms are you targeting that require `linux/arm`?

If you wanted to submit a PR that would be appreciated 👍 for reference, the PR that added arm64 support is here: https://github.com/replicatedhq/troubleshoot/pull/484

**Comment by twz123** [comment]
I'll send a PR today.

> I'm curious - what hardware platforms are you targeting that require linux/arm?

K0s targets 32-bit ARM in general, and so there's also some (basic) CI coverage for that platform. It's a reasonable choice for edge/embedded boxes, e.g. in factories.

**Comment by banjoh** [comment]
> I'll send a PR today.
> 
> > I'm curious - what hardware platforms are you targeting that require linux/arm?
> 
> K0s targets 32-bit ARM in general, and so there's also some (basic) CI coverage for that platform. It's a reasonable choice for edge/embedded boxes, e.g. in factories.

...and Raspberry PIs. Thanks for raising this.
