### ISSUE TITLE
Allow to template the Pre-Flight & SupportBundle Yaml and set from values the cli

### ISSUE THREAD

**Issue by donmstewart** [replicatedhq/troubleshoot#1103]
Would it be possible to template the Pre-Flight & Support-Bundle yaml files in a similar manner to Helm/GoTemplate so something like `--set variable=value` is possible at runtime.

For an app deployed with something like Helm constructs such as Namespace, Deployment/Statefulset Replica Counts etc. are variable and not something we can fix in the Pre-Flight & Support-Bundle tests. We could ask ops/customers to hand edit yaml files but it would be nicer if the values can be set at runtime from the cli.

**Comment by chris-sanders** [comment]
That's great question we've been discussing what that would look like as well. As a first pass we are currently looking to implement input via stdin so that you could so things like `helm template . -f | support-bundle` which would then work if for whatever your preferred templating system is (helm, kustomize, etc).

@banjoh is working on scoping that now and would probably be interested to hear more about your use case and if this will resolve what you're trying to solve.

**Comment by donmstewart** [comment]
We deploy our product internally as well as it being an in cloud & on-prem public offer. However, there are many different combinations of configuration and sizing of the installations along with diverse cloud and bare metal Kubernetes platforms.

The customer can tailor namespace settings, number of replicas and many other settings etc. during installation. This means a number of the current SupportBundle fields would vary every time we need someone to run it and that means not just running over http but the need to pull the rules by downloading and editing. It would be nice to allow the cli run over http, as in your examples by an end-user, and set the sam set of values to support-bundle as they did on the initial installation.

**Comment by chris-sanders** [comment]
Are you aware of the ability to install the bundle in the cluster?

What I was implying here is that you would template your bundles with your application allowing you to set the values based on the values file for that particular install. Before the install you can (once implemented) pipe the templates into support bundle to do a pre-flight if you like and after the install you can use the [discover-cluster-specs](https://troubleshoot.sh/docs/support-bundle/discover-cluster-specs/) feature to run the support bundle that has already been customized for that particular environment.

**Comment by donmstewart** [comment]
No I had not noticed that. Thanks for the prompt reply and link. I will be sure to take a look at that.

**Comment by xavpaice** [comment]
It's worth pointing you at #1108 also, we're working on getting the yaml into the Helm chart itself, to make all this easier.

**Comment by banjoh** [comment]
Noting that our current efforts are leaning towards a workflow that relies on an external tool such as helm or kustomize performing template evaluation, I'd be interested to know if your initial intention/use case was to use troubleshoot standalone. We have templating dotted around troubleshoot such as with the [pod status analyser](https://troubleshoot.sh/docs/analyze/cluster-pod-statuses/#example-analyzer-definition) where spec templates are evaluated using collected data, but we do not have a case where we support evaluating spec template placeholders using provided user input.

We have a rejected PR (https://github.com/replicatedhq/troubleshoot/pull/797) which aimed to introduce `kubectl preflight preflight.yaml --values values.yaml`. This will be succeeded by relying on an external templating tool (e.g helm) doing the job and then piping the output as has been mentioned in comments above.

**Comment by xavpaice** [comment]
Note: it is possible now to use Helm to template values in preflight as it now accepts stdin:

```
helm template ./chart --set-string generatePreflights=true --values values.yaml | kubectl preflight -

```

You would need to use an `{{ if` around the preflight spec, and only render it if `generatePreflights` is true.

There is another issue to implement this same logic in support-bundle, however that is currently lower in our priority list than preflight given that we already support in-cluster specs in secrets for support-bundle.

I'll close this now - unless you have a use-case that doesn't match up with the above?
