### ISSUE TITLE
Allow `preflight`binary to accept stdin as well as URI and files for spec input

### ISSUE THREAD

**Issue by xavpaice** [replicatedhq/troubleshoot#1109]
The `preflight` binary currently does not accept stdin as a method to pass yaml documents containing Troubleshoot specs.

This task is to add that ability.

Definition of done:

- [x] `preflight` accepts stdin such that `cat mypreflight.yaml | kubectl preflight` produces the output of preflights from mypreflight.yaml
- [x] the content of stdin can be multiple yaml documents, each containing a valid preflight(s), results are from a merged spec
- [ ] Docs are updated in troubleshoot.sh and/or docs.replicated.com

Out of scope:
- Ability to mix stdin and other URI types of input

**Comment by danj-replicated** [comment]
to be consistent with kubectl, should we approach this the same way kubectl does with `-` to reference stdin ?

**Comment by danj-replicated** [comment]
for example, by adding a url keyword of `-` that asks preflight to read from `/dev/stdin` we can proceed with minimal changes to the preflight package itself and how it loads the preflight specs

**Comment by chris-sanders** [comment]
Unless there's a technical issue with it I think matching what kubectl does is generally our intention. I'm in favor of doing it this way.

**Comment by xavpaice** [comment]
TODO: docs

**Comment by xavpaice** [comment]
Documented in https://troubleshoot.sh/docs/preflight/cli-usage/
