### ISSUE TITLE
Filter incoming yaml documents to `preflight` to only respond to valid preflights

### ISSUE THREAD

**Issue by xavpaice** [replicatedhq/troubleshoot#1111]
There are circumstances, e.g. when using the output of `helm template`, when many documents are fed to `preflight` and only a portion of them are valid for use as specs.  We should be able to filter incoming docs, via stdin or from a URI path (including local files) such that we only process docs that are:

* match both `apiVersion: troubleshoot.sh/v1beta*` and `kind: Preflight`
* or, a secret or configMap that has the label `troubleshoot.io/kind: preflight`(or updated by #1070)

The second option here extends the work in #1110 to match not just secrets stored in-cluster, but provided as yaml as manifests on the command line.

Definition of done:

- [ ] `preflight` can be passed multiple yaml documents of varying formats, and only processes those listed above
- [x] if multiple documents/specs/secrets are selected for processing, these are merged
- [ ] if there is a `kind: Prefight` document provided as well as a secret containing a spec, these are both selected for processing and merged.
- [ ] Docs updated

Out of scope:
- there is no requirement to support both URI and stdin on the same command-line call.

**Comment by danj-replicated** [comment]
this will have to be addressed in https://github.com/replicatedhq/troubleshoot/issues/1109 to avoid erroring out whenever preflight can't decode input into valid preflight manifests

**Comment by xavpaice** [comment]
Let's do the first iteration where we only respond to `kind: Preflight` and not the secrets/configMaps.

**Comment by xavpaice** [comment]
I'm closing this as #1114 covers the minimum scope that turned out to be what we need
