### ISSUE TITLE
Add "standard in" support to support-bundle

### ISSUE THREAD

**Issue by danj-replicated** [replicatedhq/troubleshoot#1134]
**Describe the rationale for the suggested feature.**

the `preflight` binary now supports stdin, we should add support to `support-bundle` for consistency

**Describe the feature**

`support-bundle` should allow specs to be read in from stdin. like so:

```bash
some-generating-command | support-bundle -
```

**Comment by xavpaice** [comment]
This should additionally support the same items that preflight does - finding specs in secrets and configmaps with the appropriate label also.

**Comment by xavpaice** [comment]
I think we can add this to #933 rather than add it directly to `support-bundle`
