### ISSUE TITLE
Troubleshoot Host Collector - System Packages Version Compare

### ISSUE THREAD

**Issue by chasehainey** [replicatedhq/troubleshoot#1136]
**Describe the rationale for the suggested feature.**

The host collector for system packages allows you to reference {{ .Version }} of a system package, but you're unable to do a comparison for if you need the package to be at least a certain version or not.

**Describe the feature**

Be able to do comparisons like (for MySQL):
{{ .Version }} > 5.7.41-0ubuntu0.18.04.1
{{ .Version }} >= 5.7.41-0ubuntu0.18.04.1
{{ .Version }} < 5.7.41-0ubuntu0.18.04.1
{{ .Version }} <= 5.7.41-0ubuntu0.18.04.1

**Describe alternatives you've considered**

**Additional context**

A vendor has requested this feature

**Comment by chris-sanders** [comment]
@chasehainey out of curiosity is a simple workaround to just use > or < with the prior/next version or is that problematic for some reason?
