### ISSUE TITLE
Cluster resources collector ignores some resource types

### ISSUE THREAD

**Issue by tstephen-relx** [replicatedhq/troubleshoot#1157]
**Describe the rationale for the suggested feature.**

[Cluster resources collector](https://troubleshoot.sh/docs/collect/cluster-resources/) does not cover:
- `daemonsets`
- `leases`
- `service accounts`

**Describe the feature**

Enumerate each of these just as is done for other resource types. All three have namespaces so should be exported to a folder with each file containing just one namspace's contents.

**Describe alternatives you've considered**

We are forced to fall back to kubectl commands because of these missing items.

**Additional context**

N/A

**Comment by xavpaice** [comment]
Related: this could use sbctl support too (TODO write an issue for that)
