### ISSUE TITLE
Document ClusterResource Analyzer

### ISSUE THREAD

**Issue by diamonwiggins** [replicatedhq/troubleshoot#1161]
**Describe the rationale for the suggested feature.**

We should document the analyzer added in https://github.com/replicatedhq/troubleshoot/pull/780

**Comment by diamonwiggins** [comment]
Something we should mention in these docs - https://github.com/replicatedhq/troubleshoot/pull/1189#discussion_r1210579830

**Comment by xavpaice** [comment]
https://github.com/replicatedhq/troubleshoot.sh/pull/503 implemented docs
