### ISSUE TITLE
Default label for support-bundles cannot be deployed by Helm

### ISSUE THREAD

**Issue by xavpaice** [replicatedhq/troubleshoot#1164]
**Bug Description**

The default label that Troubleshoot uses to search for support bundle specs is `troubleshoot.io/kind=support-bundle`.  When I put this in a Helm chart, e.g.

```yaml
  labels:
    troubleshoot.io/kind=support-bundle
```

Attempting to render (`helm template`) or deploy the chart results in an error:

```
invalid type for io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta.labels: got "string", expected "map"
```

**Expected Behavior**

I should be able to supply the default label in a Helm definition.

**Steps To Reproduce**

as above

**Additional Context**

Include the following information.

We have noted that `troubleshoot.io` is a domain not known by Replicated, and should be changed to `troubleshoot.sh` in any case.

KOTS uses labels to search for secrets, however it is using `kots.io/kind: supportbundle` rather than the default.

**Comment by xavpaice** [comment]
I would like to see us replace the default with `troubleshoot.sh/kind: support-bundle`.

**Comment by danj-replicated** [comment]
>When I put this in a Helm chart, e.g.
>
>  ```
> labels:
>    troubleshoot.io/kind=support-bundle
> ```
>
>Attempting to render (helm template) or deploy the chart results in an error:
>
> `invalid type for io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta.labels: got "string", expected "map"`

That would be because `troubleshoot.io/kind=support-bundle` is the selector syntax and not a valid yaml map, 

using the label `troubleshoot.io/kind: support-bundle` and runnning `kubectl get secrets -l troubleshoot.io/kind=support-bundle` returns the secret as expected

**Comment by xavpaice** [comment]
total PEBKAC.  Apologies!
