### ISSUE TITLE
Feature: add ability to check PVC minimum size

### ISSUE THREAD

**Issue by ghost** [replicatedhq/troubleshoot#1178]
**Describe the rationale for the suggested feature.**

Add in the ability to check if a PVC has a minimum amount of storage space. 
Currently, the clusterResource analyzer only supports the == operator.

**Comment by diamonwiggins** [comment]
Will close in favor of #1195

**Comment by CpuID** [comment]
This was resolved in https://github.com/replicatedhq/troubleshoot/pull/1210

Released in Troubleshoot v0.68.0 https://github.com/replicatedhq/troubleshoot/releases/tag/v0.68.0

The example documented here covers how it can be used https://troubleshoot.sh/docs/analyze/cluster-resource/#example-analyzer-definition
