### ISSUE TITLE
support bundle generation hangs indefinitely if pod creation fails due to CNI issues

### ISSUE THREAD

**Issue by CpuID** [replicatedhq/troubleshoot#1188]
**Bug Description**

When running troubleshoot via `kubectl support-bundle https://raw.githubusercontent.com/replicatedhq/troubleshoot-specs/main/in-cluster/default.yaml` to generate a support bundle, if the `troubleshoot-copyfromhost-*` pod/s fail to start due to CNI issues, it will retry + hang indefinitely.

**Expected Behavior**

Eventually `support-bundle` should give up here, bonus points for showing the pod events for any relevant `Terminating` pods. Single digit minutes feels like the right number to wait, or maybe X attempts to start the pod without success? We saw 9~ pods sitting in `Terminating` in the report from our customer.

**Steps To Reproduce**

- Break the CNI on a node (eg. a failed weave -> flannel migration)
  - better steps TBC here
- `kubectl support-bundle https://raw.githubusercontent.com/replicatedhq/troubleshoot-specs/main/in-cluster/default.yaml`

**Additional Context**

Troubleshoot 0.65.0
RHEL 8.7

**Comment by DexterYan** [comment]
After testing, 

There are two problems.
1. copyFromHost collector: this collector has default timeout, so it will not block the troubleshoot.sh. However, after a certain time, those running ` troubleshoot-copyfromhost-*` will stuck in `Terminating` forever.
2. runPod collector: this collector does not have default timeout, so it will use runWithoutTimeout as default. This will block the whole troubleshoot.sh process.

Solutions:
we need to introduce a force delete for all those terminating pods, and also add a CNI check after creating a daemon set or pod.
