### ISSUE TITLE
filesystemPerformance check false alarms

### ISSUE THREAD

**Issue by xavpaice** [replicatedhq/troubleshoot#1215]
**Bug Description**

When running HostPreflight checks, the filesystemPerformance check returns a warning for disk latency on an instance that appears to be fine if we ignore the warning.

**Expected Behavior**

Do not warn unless there's a genuine performance issue.

**Steps To Reproduce**

Instance types:
* AWS EC2 us-west-2 m5.4xlarge with EBS block store
* t3.xlarge and a gp2 volume

Measured results with the collector in https://github.com/replicatedhq/kURL/blob/e17edc5d2971fda3f0a1f168cae7aa6ce8e7b5df/pkg/preflight/assets/host-preflights.yaml#L512-L513:

```
[WARN] Filesystem Performance: Write latency is high. p99 target < 10ms, actual:
   Min: 1.249011ms
   Max: 219.425382ms
   Avg: 3.64555ms
    p1: 1.408942ms
    p5: 1.526009ms
   p10: 1.602084ms
   p20: 1.709857ms
   p30: 1.798301ms
   p40: 1.884261ms
   p50: 1.976585ms
   p60: 2.074297ms
   p70: 2.193705ms
   p80: 2.370422ms
   p90: 2.740913ms
   p95: 3.383787ms
   p99: 66.95246ms
 p99.5: 85.128422ms
 p99.9: 140.532147ms
p99.95: 155.877727ms
p99.99: 185.874478ms
```

**Additional Context**

This is potentially an issue with the warm up time, which currently defaults to 10s. 

Things to try:
* run the test 3-4 times in a row, with no gap between - and compare the results
* increase the warmup to 30s or more
* compare the results from the collector against fio, and other similar common tools

**Comment by adamancini** [comment]
https://github.com/kastenhq/kubestr could get us a Go library to `fio` which could give us a more flexible benchmark on storage

https://pkg.go.dev/github.com/kastenhq/kubestr/pkg/fio

**Comment by adamancini** [comment]
I played with `kubestr` a little bit and the way it works is that it runs `fio` with a storageclass and then runs various jobs against a PVC - it looks like their library is not an implementation of `fio` but mostly the CLI interface to get jobs running against that PVC - ~I think it packages a precompiled `fio` to run~ and it runs `fio` in a pod.  Not sure if this is exactly what we need.

**Comment by adamancini** [comment]
https://etcd.io/docs/v3.4/faq/#system-requirements links to https://www.ibm.com/cloud/blog/using-fio-to-tell-whether-your-storage-is-fast-enough-for-etcd for that 99.99th percentile measurement of <10s or less - I think this is where we get the baseline for the test we perform in the collector

**Comment by chris-sanders** [comment]
As I recall, and @adamancini please check me on this. After the above investigations we finally decided that it's best to use the actual `fio` binary on the system and return a warning if it's missing and move on.
