### ISSUE TITLE
Store custom resources as JSON files

### ISSUE THREAD

**Issue by banjoh** [replicatedhq/troubleshoot#1218]
**Describe the rationale for the suggested feature.**

The [cluster resources collector](https://troubleshoot.sh/docs/collect/cluster-resources/) currently stores files in a mixture of `json` and `yaml` formats. Custom resources are all [`yaml` formatted](https://github.com/replicatedhq/troubleshoot/blob/620fa75eb593247a07c4dc39ea96fc6a059be111/pkg/collect/cluster_resources.go#L1283) and all the rest are `json` formatted. This makes it hard to craft analysers or redactors that target these files as well as making [`sbctl`](https://github.com/replicatedhq/sbctl) unnecessarily complicated when trying to serve k8s resources in an API from support bundles.

**Describe the feature**

There are two options we can implement to address this issue
* Choose one format and have all files formatted this way - the easy path, **preferred one cause of reduced complexity**
* ~~Add a flag that can be used to choose between `yaml` or `json` formats - the harder way~~
  * ~~This comes at a risk of not knowing what file type to expect making it harder downstream to consume data in these files~~ - Not an option due to the comment below

**Additional context**
- Redacted YAML files can end up being invalid as opposed to JSON files in certain scenarios such as when the IP redactor is used
```yaml
status:
    ip: ***HIDDEN***
```
vs
```json
{
    "ip": "***HIDDEN***"
}
```

**Comment by xavpaice** [comment]
Does this mean sbctl cannot read the custom resources?

**Comment by banjoh** [comment]
> Does this mean sbctl cannot read the custom resources?

Yes. You cannot read any of the custom resources collected for example e.g in an sbctl shell `kubectl get installers` which should have the kURL installer spec will error
