### ISSUE TITLE
Preflight with no spec returns an unhelpful error

### ISSUE THREAD

**Issue by xavpaice** [replicatedhq/troubleshoot#1236]
When we run `preflight` without providing a spec, e.g. when using `helm template somechart |preflight -`, folks are seeing an error message:

```
❯ helm template oci://registry.replicated.com/ghost-bird/unstable/ghost | kubectl preflight -
Pulled: registry.replicated.com/ghost-bird/unstable/ghost:19.3.18
Digest: sha256:bea02ddf89e923e7aee399fdc953259a6fa5a59c5fc287741d9c897a866c2487
Error: no results
```

The return code is 1.

Folks would like to see a more useful message, e.g.:

```
OK: no preflight spec was provided
```

The exit code for `preflight` executed with no spec should return 0 (OK) - i.e. no analyzer failed.  This allows folks to use the steps in a CI/CD system regardless of whether there is a preflight, and then when the preflight is added it automatically picks up any failures.

**Comment by dexhorthy** [comment]
(pulling question from SC) @xavpaice is there a way for us to detect if a spec is present but all collectors / analyzers are filtered out by `exclude` or `.Values` evaluation? In that case we should not show `no preflight spec was provided`

**Comment by xavpaice** [comment]
@dexhorthy what `preflight` sees when we use `helm template xyz |preflight -` is the stream of stdout from `helm template` - at that stage, there's no templating, values.yaml or anything like that, just what Helm rendered. So, in short, no unfortunately we can't tell what was excluded from the render by the command prior to preflight.

**Comment by xavpaice** [comment]
this is the same as #227
