### ISSUE TITLE
Intermittent test failures with jsonpath_comparison,_multiple_values

### ISSUE THREAD

**Issue by xavpaice** [replicatedhq/troubleshoot#1274]
**Bug Description**

During test runs, we see intermittent failures reporting:

```
=== RUN   Test_jsonCompare/jsonpath_comparison,_multiple_values
    json_compare_test.go:699: 
        	Error Trace:	/home/runner/work/troubleshoot/troubleshoot/pkg/analyze/json_compare_test.go:699
        	Error:      	Not equal: 
        	            	expected: analyzer.AnalyzeResult{IsPass:true, IsFail:false, IsWarn:false, Strict:false, Title:"jsonpath-compare-2", Message:"pass", URI:"", IconKey:"kubernetes_text_analyze", IconURI:"https://troubleshoot.sh/images/analyzer-icons/text-analyze.svg", InvolvedObject:(*v1.ObjectReference)(nil)}
        	            	actual  : analyzer.AnalyzeResult{IsPass:false, IsFail:true, IsWarn:false, Strict:false, Title:"jsonpath-compare-2", Message:"fail", URI:"", IconKey:"kubernetes_text_analyze", IconURI:"https://troubleshoot.sh/images/analyzer-icons/text-analyze.svg", InvolvedObject:(*v1.ObjectReference)(nil)}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,4 +1,4 @@
        	            	 (analyzer.AnalyzeResult) {
        	            	- IsPass: (bool) true,
        	            	- IsFail: (bool) false,
        	            	+ IsPass: (bool) false,
        	            	+ IsFail: (bool) true,
        	            	  IsWarn: (bool) false,
        	            	@@ -6,3 +6,3 @@
        	            	  Title: (string) (len=18) "jsonpath-compare-2",
        	            	- Message: (string) (len=4) "pass",
        	            	+ Message: (string) (len=4) "fail",
        	            	  URI: (string) "",
        	Test:       	Test_jsonCompare/jsonpath_comparison,_multiple_values
--- FAIL: Test_jsonCompare (0.00s)
```

This test appears to be performing a recursive search using jsonpath and `JsonPath:      "{$..bar}",`.  The result returned is expected to be ```Value: `[true, 123]`,``` however in some runs, that's not the case.

**Expected Behavior**

Tests pass consistently.

**Steps To Reproduce**

Run unit tests often.

**Additional Context**

**Comment by DexterYan** [comment]
The test case has two outcomes. One is pass, one is fail.
```
{
	name: "jsonpath comparison, multiple values",
	analyzer: troubleshootv1beta2.JsonCompare{
		Outcomes: []*troubleshootv1beta2.Outcome{
			{
				Pass: &troubleshootv1beta2.SingleOutcome{
					Message: "pass",
				},
			},
			{
				Fail: &troubleshootv1beta2.SingleOutcome{
					Message: "fail",
				},
			},
		},
		CollectorName: "jsonpath-compare-2",
		FileName:      "jsonpath-compare-2.json",
		JsonPath:      "{$..bar}",
		Value:         `[true, 123]`,
},
```
If you leave only one outcome with fail, then you can reproduce this error in local

**Comment by DexterYan** [comment]
In https://github.com/replicatedhq/troubleshoot/blob/8237ac991cc935a3c76d06fdb26db41d28c8b983/pkg/analyze/json_compare.go#L100
```
equal := reflect.DeepEqual(actual, expected)
fmt.Println(actual)
fmt.Println(expected)
```

actual is `[123 true]`
expected is `[true 123]`

**Comment by DexterYan** [comment]
<img width="2087" alt="Screenshot 2023-07-20 at 6 41 45 PM" src="https://github.com/replicatedhq/troubleshoot/assets/5716585/8aac0f6a-89c5-473b-b448-d99dbb16c2f9">
It is random happen. You can tested in locally by few times.

**Comment by banjoh** [comment]
This is happening cause of how maps work on golang. Keys are unordered leading to [jsonpath.Execute()](https://github.com/replicatedhq/troubleshoot/blob/8237ac991cc935a3c76d06fdb26db41d28c8b983/pkg/analyze/json_compare.go#L69) returning found results in different order. We'd need handle the case where `[123 true]` and `[true 123]` are equal.

**Comment by banjoh** [comment]
Here is my initial implementation of my thought above.

https://github.com/banjoh/troubleshoot/commit/b0a45752c0c5f9136e8f658d16f6e0a1453232e1

I do not think comparisons would be an issue if the result is a JSON object (`map`), even if the map has slices in them. Some testing is needed.

**Comment by DexterYan** [comment]
Hey @banjoh, the pr #1300 is ready to review, could you help me to check?
