### ISSUE TITLE
Helm Install History

### ISSUE THREAD

**Issue by CpuID** [replicatedhq/troubleshoot#1285]
**Describe the rationale for the suggested feature.**

Being able to troubleshoot errors like this from support bundles:

```
 Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress
```

**Describe the feature**

We should add a collector for Helm Release History, a la:

```
helm ls -a --namespace <namespace>
helm history <release> --namespace <namespace>
```

https://ibm.github.io/helm101/Lab3/#scenario-2-revision-management-using-helm

> With Helm, every time an install, upgrade, or rollback happens, the revision number is incremented by 1. The first revision number is always 1. Helm persists release metadata in Secrets (default) or ConfigMaps, stored in the Kubernetes cluster. Every time your release changes, it appends that to the existing data. This provides Helm with the capability to rollback to a previous release.

**Describe alternatives you've considered**

Having a customer run the commands manually, less than ideal. Would be nice to have the data in support bundles.

**Additional context**

**Comment by drohnow** [comment]
@CpuID What are your thoughts on collecting the following information in this json format?

```
[{
	"releaseInfo": {
		"chart": "big_app-0.1.1",
		"releaseName": "prod01",
		"appVersion": "0.16.0",
		"namespace": "default",
		"versionInfo": [{
				"revision": "1",
				"date": "2023-07-02 05:05:43.201063 -0700 PDT",
				"status": "superseded",
				"isPending": false,
				"description": "Install complete"
			},
			{
				"revision": "2",
				"date": "2023-08-02 07:18:37.201041 -0700 PDT",
				"status": "deployed",
				"isPending": false,
				"description": "Upgrade complete"
			}
		]
	}
}]

```

**Comment by CpuID** [comment]
that seems reasonable 👍
