### ISSUE TITLE
Redactors in v0.71.1 consume too much memory

### ISSUE THREAD

**Issue by banjoh** [replicatedhq/troubleshoot#1331]
**Bug Description**

In certain scenarios, running redactor when collector a support bundle can consume a lot of memory leading to OOM signals killing pods.

Here is are memory profiles of this happening in [KOTS ](https://github.com/replicatedhq/kots).

**With v0.71.1**
![Screen Shot 2023-09-08 at 10 26 46 AM](https://github.com/replicatedhq/troubleshoot/assets/681087/854a1ff0-9fa5-4534-8286-4c51a8e6fe03)

**With v0.70.3**
![Screen Shot 2023-09-08 at 10 23 20 AM](https://github.com/replicatedhq/troubleshoot/assets/681087/1bb2c8ac-c6a2-42e4-87d6-eb167fc2c33d)

~~NOTE: This has not been reproduced when using the CLI.~~ From comments below

- Checkout `v0.71.1` of troubleshoot
- Build binaries `make build`
- Collect and redact support bundle - `./bin/support-bundle ./support-bundle.yaml --memprofile=mem.conf --redactors ./redactor.yaml` with [support-bundle.yaml](https://github.com/replicatedhq/troubleshoot/files/12563266/support-bundle.yaml.txt) and [redactor.yaml](https://github.com/replicatedhq/troubleshoot/files/12563268/redactor.yaml.txt)
- Analyse memory allocations - `go tool pprof -http :8888 -alloc_space mem.prof` will start an http server on port 8888 

**Expected Behavior**

Redaction code should not consume excess memory.

**Steps To Reproduce**

Include the commands to reproduce the issue including any output. Any information that will help us to understand the problem is useful.  Feel free to paste long output into a [Github gist](https://gist.github.com) and include the link here.

To be fleshed

**Additional Context**

Include the following information.
- Troubleshoot version. If you built from source, note that including the version of Go you used to build with.
- Operating system
- Operating system version
- Other details that might be helpful in diagnosing the problem

**Comment by arcolife** [comment]
For context, as first seen in testsuite while bumping troubleshoot to v0.71.1 in kots https://github.com/replicatedhq/kots/pull/4031

And PR relevant to investigation https://github.com/replicatedhq/troubleshoot/pull/1291

Potentially helpful tooling https://github.com/replicatedhq/troubleshoot/issues/1301

Discussion (internal - all info is summarized above) https://replicated.slack.com/archives/C016DU6CXNE/p1694185342225949

**Comment by chris-sanders** [comment]
@banjoh did you get the images backwards?

**Comment by cbodonnell** [comment]
The higher memory consumption can also be reproduced from the CLI:

1. Modify the `cmd/troubleshoot/main.go` function so that it generates a memory profile (might be a better way to do this without rebuild the binary, but this is how I got it working):
```
func main() {
	cli.InitAndExecute()

	memProfileFile, err := os.Create("mem.prof")
	if err != nil {
		panic(err)
	}
	defer memProfileFile.Close()

	if err := pprof.WriteHeapProfile(memProfileFile); err != nil {
		panic(err)
	}
}
```

2. `make support-bundle`
3. `./bin/support-bundle ./support-bundle.yaml --redactors ./redactor.yaml` with [support-bundle.yaml](https://github.com/replicatedhq/troubleshoot/files/12563266/support-bundle.yaml.txt) and [redactor.yaml](https://github.com/replicatedhq/troubleshoot/files/12563268/redactor.yaml.txt)
4. `go tool pprof -http :8888 -alloc_space mem.prof` will start an http server on port 8888 where you can view the details
