### ISSUE TITLE
Some collectors may be using old apiVersions on `podDisruptionBudget` and `cronJob` collection

### ISSUE THREAD

**Issue by adamancini** [replicatedhq/troubleshoot#1370]
**Bug Description**

GKE cluster dashboard reports that the `ReplicatedTroubleshoot` useragent is hitting some deprecated APIs and generating warning banners.

**Expected Behavior**

Troubleshoot does not generate API errors due to deprecated APIs.

**Steps To Reproduce**

Log into `replicated-qa` on GCP and navigate to Clusters - drill into a cluster:

<img width="765" alt="Screenshot 2023-10-13 at 14 54 12" src="https://github.com/replicatedhq/troubleshoot/assets/292598/2f273432-4b06-4b9b-8792-98e07615137b">

**Comment by adamancini** [comment]
Need to confirm that these are indeed coming from troubleshoot; I'm just going on the assumption that the userAgent is correct.

**Comment by adamancini** [comment]
Ex:

```
func getPodDisruptionBudgets(ctx context.Context, client *kubernetes.Clientset, namespaces []string) (map[string][]byte, map[string]string) {
	ok, err := discovery.HasResource(client, "policy.k8s.io/v1", "PodDisruptionBudgets")
	if err != nil {
		return nil, map[string]string{"": err.Error()}
	}
	if ok {
		return pdbV1(ctx, client, namespaces)
	}

	return pdbV1beta(ctx, client, namespaces)
}
```


It looks like we already use some logic to figure out the apiVersion, but need to determine where the erroneous API calls come from

**Comment by nvanthao** [comment]
I think the beta API is called because we used wrong group. Instead of `policy.k8s.io/v1` and `batch.k8s.io/v1`, it should be `policy/v1` and `batch/v1`
