### ISSUE TITLE
Some troubleshoot.sh types are missing the uri parameter

### ISSUE THREAD

**Issue by banjoh** [replicatedhq/troubleshoot#1557]
**Bug Description**

Troubleshoot.sh is designed to allow [specs to be updatable](https://github.com/replicatedhq/troubleshoot/blob/main/docs/design/proposal-updateable-specs.md) using a `uri` parameter. This parameter would have a url pointing to the spec updates.

Not all top level type (types that collect analysers/collectors/redactors together) have this field defined. Here is the current state of affairs

| Type  | Has URI field |
| ----------------- | ------------- |
| Analyzer 	       | ❌ |
| Collector 	       | ❌ |
| HostCollector       | ❌ |
| HostPreflight        | ❌ |
| Preflight 	        | ❌ |
| Redactor 		| ❌ |
| RemoteCollector 	| ❌ |
| SupportBundle 	| ✅ |

**Expected Behavior**

All top level types need to have this field defined.

**Additional Context**

Tools that support updating specs need to check that the external spec being dowloaded is of the same kind.

**Comment by alexparker215** [comment]
@banjoh Is there also an issue open to address the fact that an unknown analyzer will look like a failure to an end-user?

**Comment by banjoh** [comment]
> @banjoh Is there also an issue open to address the fact that an unknown analyzer will look like a failure to an end-user?

We do. https://github.com/replicatedhq/troubleshoot/issues/1436. The description focuses on formatting of a spec but the issue is similar to a misspelled analyser in the spec which would be a non-existent one.
