### ISSUE TITLE
exec collector is running in all pods matched the selector

### ISSUE THREAD

**Issue by nvanthao** [replicatedhq/troubleshoot#1568]
**Bug Description**

Our [doc](https://troubleshoot.sh/docs/collect/exec/) states that
>When the selector refers to more than one replica of a pod, the exec collector will execute in only one of the pods

**Expected Behavior**
Only exec in 1 pod rather than all pods matched the selector

**Steps To Reproduce**
- Run exec collector to a Deployment with 2 replicas
- Notice exec are running in 2 pods

**Additional Context**
- Troubleshoot version: `0.93.2`

https://github.com/replicatedhq/troubleshoot/blob/53113c0170ce4d1d02ef7552e5cebdc5ae6d4feb/pkg/collect/exec.go#L86-L92

**Comment by xavpaice** [comment]
Is this a bug in the collector, or the docs?  I would have expected a deployment with 2 replicas to run 2.
