### ISSUE TITLE
Documentation inconsistent on distribution analyzer

### ISSUE THREAD

**Issue by chris-sanders** [replicatedhq/troubleshoot#1580]
**Bug Description**

See: https://troubleshoot.sh/docs/analyze/distribution/

The documenation at the top uses:
digitalOceaion and dockerDesktop

The spec at the bottom has the correct:
digitalocean and docker-desktop

**Comment by xavpaice** [comment]
Next steps, find the correct usage, and update the docs [here](https://github.com/replicatedhq/troubleshoot.sh/blob/main/docs/source/analyze/distribution.md)

**Comment by xavpaice** [comment]
Fixed with PR
