### ISSUE TITLE
cannot find module providing package 

### ISSUE THREAD

**Issue by qicz** [replicatedhq/troubleshoot#1643]
**Bug Description**

 go build but occur the error like follow(same with `-mod=vendor`):

`vendor/github.com/replicatedhq/troubleshoot/pkg/collect/mssql.go:12:2: cannot find module providing package github.com/microsoft/go-mssqldb: import lookup disabled by -mod=vendor`

**Comment by qicz** [comment]
create a symbol link by `ln` like `ln -s /vendor/github.com/Microsoft /vendor/github.com/microsoft` works.

**Comment by xavpaice** [comment]
Thanks for the report.  Could you let us know the process you're working through to perform the build?  We use the Makefile to drive builds, which may help.
