### ISSUE TITLE
Filepath handling on Windows

### ISSUE THREAD

**Issue by ashwathishiva** [replicatedhq/troubleshoot#165]
This bug is related to preflight running on Windows. When gathering cluster-version, specifically.

In Windows, when I have an analyzer for checking the cluster version, preflight fails because it is not able to collect the `cluster_version.json` file.
Here is the  error: 
```
failed to get the contents of cluster_version.json: file cluster-info/cluster_version.json was not collected
```
Looks like filepath not being handled appropriately on Windows. Investigated the contents of the map `c.AllCollectedData` and found a key in it which matches `cluster-info\cluster_version.json`.

I was able to debug this to some extent:
In `pkg/preflight/analyse.go` :
```
func (c CollectResult) Analyze() []*analyze.AnalyzeResult {
	getCollectedFileContents := func(fileName string) ([]byte, error) {...
```

Hope this helps.

**Comment by manavellamnimble** [comment]
@marccampbell it seems like this bug was already fixed with PR https://github.com/replicatedhq/troubleshoot/pull/162
