### ISSUE TITLE
Allow TextAnalyzer to scan multiple files

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/troubleshoot#173]
Currently the TextAnalyzer requires both a CollectorName and a Filename param. The filename is required.

This is hard to use when scanning the logs of a deployment or statefulset because the filenames are not deterministic. 

The TextAnalyzer should allow filename to contain wildcard characters, and it will search all filenames in the collectorName that match the wildcard.

**Comment by dexhorthy** [comment]
@laverya @marccampbell any update on this? This makes textanalyzer pretty tricky to use. Either via wildcard or by file labels?
