### ISSUE TITLE
Analyzer for default storage class?

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/troubleshoot#200]
Right now we can check for a storage class with a given name, but what if I just want to check for a storage class that has the `isDefaultStorageClass` field set to true? In most cases I don't care what the end user is calling their storage class and I want to reduce friction by leaving `storageClassName` empty in my PVCs and StatefulSets, and just use a preflight check to ensure there is a default storageClass to provision PVs.

**Comment by Iristyle** [comment]
+1 - just ran into this

Preflight check failed even though:

```
kubectl get storageclass
NAME                        PROVISIONER                     RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
rook-ceph-block (default)   rook-ceph.rbd.csi.ceph.com      Delete          Immediate           true                   86m
rook-cephfs                 rook-ceph.cephfs.csi.ceph.com   Delete          Immediate           true                   45m
```

**Comment by matias-manavella-nimble** [comment]
@dexhorthy @marccampbell Hi, I'm on it. It would be a good chance to use further filters for the storage classes. I will add the possibility of leaving the storageClassName empty, and check if there is any storageClass with the flag storageclass.kubernetes.io/is-default-class set to true. 

We can also add the following filters, let me know if you want me to add it:
```YAML
apiVersion : 
provisioner :
reclaimPolicy :
volumeBindingMode :
```

**Comment by matias-manavella-nimble** [comment]
@laverya could you close this issue? It is fixed with the PR you've just merged
