### ISSUE TITLE
'copy' collector should work with directories

### ISSUE THREAD

**Issue by laverya** [replicatedhq/troubleshoot#212]
Currently the [copy collector](https://troubleshoot.sh/reference/collectors/copy/) calls [cat within the container](https://github.com/replicatedhq/troubleshoot/blob/d016e3269c9e2cf055f1becb546928587c6ae470/pkg/collect/copy.go#L61), which doesn't work with directories - only individual files. This is rather suboptimal.

**Comment by matias-manavella-nimble** [comment]
Hi @laverya @markpundsack, I found a solution that would allow copy collector to get all the files in a folder and its sub-folders. But, should it have a limit? Should we not copy some specific type of file?

**Comment by markpundsack** [comment]
I don’t have any strong opinions on this. Being able to specify a pattern sounds useful too, but I do imagine some people will need to simply copy a entire directory, knowing that it only contains the kind of files they are looking for.

**Comment by matias-manavella-nimble** [comment]
@markpundsack Sound good! I've created the PR with the modifications! Let me know if there is something you would like to change!

**Comment by markpundsack** [comment]
@manavellamnimble @divolgin Did the changes include documentation?

**Comment by matias-manavella-nimble** [comment]
@markpundsack @divolgin I was about to ask about this in the chat! If you want I can ask about it on slack, so we are all in the same page

**Comment by markpundsack** [comment]
@manavellamnimble Great, go ahead and coordinate in Slack.
