### ISSUE TITLE
Some analyzers ignore `checkName`

### ISSUE THREAD

**Issue by markpundsack** [replicatedhq/troubleshoot#222]
At least `containerRuntime` and `distribution` use hard-coded names and ignore the `checkName` value.

**Comment by matias-manavella-nimble** [comment]
Hi @markpundsack ! I am about to start working on this. Please tell me if I got it right:
checkName refers to the name of a check inside a preflight check, and the program should choose a name for the check if the name is empty, given that name is an optional parameter. For example, in the case of cluster_version, the default name if checkName is empty is "Required Kubernetes Version". Is that correct?

**Comment by markpundsack** [comment]
@manavellamnimble The problem isn't when no `checkName` is specified; all checks already have defaults, IIRC. The problem is that if you specify a `checkName` in the YAML, the code ignores it and **only** uses the hardcoded name. All analyzers should respect `checkName` if present.
