### ISSUE TITLE
kind: Preflight with no analyzers shows a misleading error

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/troubleshoot#227]
With Preflight 0.38, if I run preflight checks and don't include an analyzers section, the error message is:

```
  Running Preflight checks ⠴ Error: no data has been collected
```

If Preflights require analyzers, the message should show that. If we can have a better experience with no analyzers, that's even better.

**Comment by matias-manavella-nimble** [comment]
@marccampbell Marc, afaik analyzers and its results are preflight's core, without analyzers it wouldn't make sense to run preflight at all, am I correct?
If that is so, the message could be something communicating that  to the user, and maybe a couple of links to the docs or to the preflight example to make the user experience better?

**Comment by marccampbell** [comment]
@manavellamnimble the issue is that the default collectors may reference items that aren't required by analyzers.

For example, default collectors includes clusterResources. This attempts to list all namespaces and all objects it has access to. If the only analyzer is "Kubernetes Version", the clusterResources collector is not needed, but still errors.

We should be looking at the collector data used by included analyzers, and not fail on the collect phase for preflight if the analyzers aren't going to consume the collected data that is inaccessible.

**Comment by matias-manavella-nimble** [comment]
@marccampbell Hi Marc, I tested different error-situations, and under normal circumstances, the failure of a collector only affects the correspondent analyzer, meaning that if I would only run the K8s version analyzer and the cluster resources collector fails, I would only be informed through the console ```failed to run collector cluster-resources: error_msg```, but still get the result on the interactive display.

If a specific analyzer fails, the user would be informed through the interactive display in the console. Even if its only one. 

So, the problem would be if, for example, when running only k8s version analyzer, the cluster resources collector panics. In that case execution would stop and cluster resources collector was not needed at all. 

A solution may be to exclude (using the isExclude-flag?) unnecessary collectors previous to the beginning of the collection fase.

**Comment by xavpaice** [comment]
See an example in #1173

**Comment by xavpaice** [comment]
From testing with Helm:

When we run `preflight` without providing a spec, e.g. when using `helm template somechart |preflight -`, folks are seeing an error message:

```
❯ helm template oci://registry.replicated.com/ghost-bird/unstable/ghost | kubectl preflight -
Pulled: registry.replicated.com/ghost-bird/unstable/ghost:19.3.18
Digest: sha256:bea02ddf89e923e7aee399fdc953259a6fa5a59c5fc287741d9c897a866c2487
Error: no results
```

The return code is 1.

Folks would like to see a more useful message, e.g.:

```
OK: no preflight spec was provided
```

The exit code for `preflight` executed with no spec should return 0 (OK) - i.e. no analyzer failed.  This allows folks to use the steps in a CI/CD system regardless of whether there is a preflight, and then when the preflight is added it automatically picks up any failures.

**Comment by dexhorthy** [comment]
I guess my comment would be, there's several levels of "no spec", and we might consider separate messaging / exit codes for different types or groups of type

- no secret/configmap with the right labels/annotations
- secret/configmap exists, but no preflight.yaml or `Preflight` kind in the `data` or `stringData`
- preflight.yaml exists in the `data` and is a `Preflight` kind, but contains no meaningful `analyzers` (e.g., templated by helm to be empty, but not necessarily empty in every case)


```
spec:
  collectors: []
  analyzers: []
```

- Non-empty `Preflight` kind detected in a configmap, but all conditions filtered by `exclude` (again, due to values templating of that field)

```
spec:
  collectors:
   - collector1:
        exclude: true
  analyzers:
   - analyzer1:
        exclude: true
```

**Comment by DexterYan** [comment]
I think we could use this format with Warning, still return 0
```
Warning: all collectors were excluded
Warning: all analyzers were excluded
Warning: no preflight spec was provided
```

**Comment by xavpaice** [comment]
we also need to consider that preflights are only useful with analyzers - if there are collectors, but no analyzers, there should be a warning about that (but exit 0).  We could, in fact, ignore the lack of collectors entirely since clusterResources is added automatically.

**Comment by xavpaice** [comment]
Regards secrets, I'd like to consider some linting in Troubleshoot that can check the secret exists with the right label and key, and has some kind of validation that the content is a valid spec.  This should be a public function that can be used by other projects too (including linting when creating the release).

**Comment by dexhorthy** [comment]
I'm not super dialed in on the behavior specifics, but if `Warning: all analyzers were excluded` if meant to also capture the case where none were provided, then i'd adjust the copy to


```
Warning: No analyzers found, or all analyzers were excluded by the applied values
```



Thinking of this primarily from the perspective of "how can we give a vendor a good experience learning this, without adding too much guidance than might confuse an end customer"


Aside, there doesn't seem to be consensus on the right way to say `the applied values` - for me it's a toss up between


- `the applied values`
- `the current values context`
- `the active configuration`
- `the active values`
- `the current configuration`

**Comment by DexterYan** [comment]
I have added a few examples for showing our spec validation function. I suggest we can some URLs from our docs to give users more clear guide. 

## No Analyzers
```
./bin/preflight testdata/preflightspec/troubleshoot_v1beta2_preflight_validate_empty_analyzers_gotest.yaml
Warning: No analyzers found
```

## Example Yaml
```
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: sample
spec:
  collectors:
    - clusterInfo: {}
  analyzers: []
```

**Comment by DexterYan** [comment]
## No collectors
```
./bin/preflight testdata/preflightspec/troubleshoot_v1beta2_preflight_validate_empty_collectors_gotest.yaml
Warning: No collectors found
```

## Example Yaml
```
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: sample
spec:
  collectors: []
  analyzers: []
```

**Comment by DexterYan** [comment]
## All analyzer excluded
```
./bin/preflight testdata/preflightspec/troubleshoot_v1beta2_preflight_validate_excluded_analyzers_gotest.yaml
Warning: All analyzers were excluded by the applied values
```

## Example Yaml
```
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: sample
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
  analyzers:
    - distribution:
        exclude: true
        outcomes:
          - pass:
              when: "== k3s"
              message: K3S is a supported distribution
          - warn:
              message: Unable to determine the distribution of Kubernetes
    - clusterVersion:
        exclude: true
        outcomes:
        - pass:
            message: Cluster is up to date
```

**Comment by DexterYan** [comment]
## All Collectors Excluded
```
./bin/preflight testdata/preflightspec/troubleshoot_v1beta2_preflight_validate_excluded_collectors_gotest.yaml
Warning: All collectors were excluded by the applied values
```

## Example Yaml
```
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: sample
spec:
  collectors:
    - clusterInfo: 
        exclude: true
    - clusterResources: 
        exclude: true
  analyzers:
    - clusterVersion:
        outcomes:
        - pass:
            message: Cluster is up to date
```

**Comment by DexterYan** [comment]
## No Spec
create a no spec helm chat
```
helm template oci://registry.replicated.com/dexter-yan-test/unstable/dexter-app | ./bin/preflight -          
Pulled: registry.replicated.com/dexter-yan-test/unstable/dexter-app:0.1.3
Digest: sha256:2c0428e786869541c509189611ad1523eea6d68fea89cfe409e8cb58ae6f634b
Warning: no preflight or host preflight spec was found
```
