### ISSUE TITLE
Support collecting client and helm versions

### ISSUE THREAD

**Issue by markpundsack** [replicatedhq/troubleshoot#232]
When troubleshooting some Kubernetes apps, it's useful to know things about the clients the user is using. Furthermore, since many people install via Helm, we should support various Helm information as well. 

We should add the ability to collect:

1. `kubectl` client version
1. `helm` client version
1. `helm` server version
1. Helm chart version (implies ability to specify a Helm chart)
1. Helm values
1. helm repo list 

This would help obviate tools like [KubeSOS](https://gitlab.com/gitlab-com/support/toolbox/kubesos/-/blob/master/kubeSOS.sh).

Note: client information wouldn't be accessible from embedded usage, such as in Kotsadm. I'm not sure if that's a problem, or if we should somehow make them optional, or a different type of spec completely so they're not accidentally included in Kotsadm. My first reaction is that it shouldn't be an error to include these kinds of specs in a Kotsadm definition, but to simply have Kotsadm carry on, perhaps with warnings. If combined with https://github.com/replicatedhq/troubleshoot/issues/231, this could allow a way for users to run most collectors from within the admin console, but also run them from the CLI, with some additional information.

**Comment by xavpaice** [comment]
I suggest this is added as a host collector, to be added to the spec when appropriate.

Before writing any code, we should review the exact information that is useful for troubleshooting.  Kubernetes client is clearly useful, likely the helm client, I would consider adding some environmental info like proxy configuration, etc.

Regards collecting Helm values, chart versions, etc we probably want to get a better understanding of where that data is stored and what we want to get out of it.

**Comment by xavpaice** [comment]
Unlikely to be implemented soon, will close this now.
