### ISSUE TITLE
Distribution analyzer doesn't detect https://fuga.cloud/ managed kubernetes

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/troubleshoot#235]

**Comment by matias-manavella-nimble** [comment]
@marccampbell Hi Marc, I contacted the guys from fuga.cloud to ask them if they have a way to identify their nodes (either a label or a providerID but the told me there is no such label or ID. Can we manage to get a description of a fuga.cloud managed Node?

**Comment by xavpaice** [comment]
@marccampbell I don't think it's feasible to capture every cloud provider in the market - is fuga.cloud one we consider to be a valuable addition to the list?

**Comment by xavpaice** [comment]
Unlikely to be addressed at any stage soon, I'll close this as no longer relevant.
