### ISSUE TITLE
Add support for detecting managed Kubernetes clusters in IBM cloud

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/troubleshoot#243]

**Comment by eugene-travis** [comment]
Node info to determine distribution
`apiVersion: v1

items:
- apiVersion: v1
  kind: Node
  metadata:
    annotations:
      node.alpha.kubernetes.io/ttl: "0"
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
    creationTimestamp: "2020-08-19T08:06:15Z"
    labels:
      arch: amd64
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/instance-type: u3c.2x4
      beta.kubernetes.io/os: linux
      failure-domain.beta.kubernetes.io/region: eu-de
      failure-domain.beta.kubernetes.io/zone: fra02
      ibm-cloud.kubernetes.io/external-ip: 158.177.96.99
      ibm-cloud.kubernetes.io/ha-worker: "true"
      ibm-cloud.kubernetes.io/iaas-provider: softlayer
      ibm-cloud.kubernetes.io/internal-ip: 10.194.178.161
      ibm-cloud.kubernetes.io/machine-type: u3c.2x4
      ibm-cloud.kubernetes.io/os: UBUNTU_18_64
      ibm-cloud.kubernetes.io/region: eu-de
      ibm-cloud.kubernetes.io/sgx-enabled: "false"
      ibm-cloud.kubernetes.io/worker-id: kube-bsudhljf0rbvej5nb690-myclusterfr-default-00000130
      ibm-cloud.kubernetes.io/worker-pool-id: bsudhljf0rbvej5nb690-91c7ee1
      ibm-cloud.kubernetes.io/worker-pool-name: default
      ibm-cloud.kubernetes.io/worker-version: 1.17.11_1537
      ibm-cloud.kubernetes.io/zone: fra02
      kubernetes.io/arch: amd64
      kubernetes.io/hostname: 10.194.178.161
      kubernetes.io/os: linux
      node.kubernetes.io/instance-type: u3c.2x4
      privateVLAN: "2933248"
      publicVLAN: "2933246"
      topology.kubernetes.io/region: eu-de
      topology.kubernetes.io/zone: fra02
    name: 10.194.178.161
    resourceVersion: "7650"
    selfLink: /api/v1/nodes/10.194.178.161
    uid: 3fa4e16d-43e8-4de8-9ff2-38a01d2753a8
  spec:
    providerID: ibm://843df9e8c9bd4d37931ad48e7ba87c1f///bsudhljf0rbvej5nb690/kube-bsudhljf0rbvej5nb690-myclusterfr-default-00000130
  status:
    addresses:
    - address: 10.194.178.161
      type: InternalIP
    - address: 158.177.96.99
      type: ExternalIP
    - address: 10.194.178.161
      type: Hostname
    allocatable:
      cpu: 1920m
      ephemeral-storage: "99894567244"
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      memory: 2923348Ki
      pods: "110"
    capacity:
      cpu: "2"
      ephemeral-storage: 102687672Ki
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      memory: 4033364Ki
      pods: "110"
    conditions:
    - lastHeartbeatTime: "2020-08-19T08:36:07Z"
      lastTransitionTime: "2020-08-19T08:06:15Z"
      message: kubelet has sufficient memory available
      reason: KubeletHasSufficientMemory
      status: "False"
      type: MemoryPressure
    - lastHeartbeatTime: "2020-08-19T08:36:07Z"
      lastTransitionTime: "2020-08-19T08:06:15Z"
      message: kubelet has no disk pressure
      reason: KubeletHasNoDiskPressure
      status: "False"
      type: DiskPressure
    - lastHeartbeatTime: "2020-08-19T08:36:07Z"
      lastTransitionTime: "2020-08-19T08:06:15Z"
      message: kubelet has sufficient PID available
      reason: KubeletHasSufficientPID
      status: "False"
      type: PIDPressure
    - lastHeartbeatTime: "2020-08-19T08:36:07Z"
      lastTransitionTime: "2020-08-19T08:06:35Z"
      message: kubelet is posting ready status. AppArmor enabled
      reason: KubeletReady
      status: "True"
      type: Ready
    daemonEndpoints:
      kubeletEndpoint:
        Port: 10250
    images:
    - names:
      - registry.eu-de.bluemix.net/armada-master/node@sha256:ebf85ef4b604dd7eacfda4525338490872b1ac5ceae5affb0b6f14de34cc34f5
      - registry.eu-de.bluemix.net/armada-master/node:v3.12.2
      sizeBytes: 89710502
    - names:
      - registry.eu-de.bluemix.net/armada-master/cni@sha256:cff126929f3180d4a35662d10b6e5a78aa76011dff851f626beb28a7e8ea7e9e
      - registry.eu-de.bluemix.net/armada-master/cni:v3.12.2
      sizeBytes: 77500843
    - names:
      - registry.eu-de.bluemix.net/armada-master/ingress@sha256:edf946bce0cf8cbde06d48341e09afd0afc462822db4d2d0901944bf375553a4
      - registry.eu-de.bluemix.net/armada-master/ingress:647
      sizeBytes: 49406062
    - names:
      - registry.eu-de.bluemix.net/armada-master/haproxy@sha256:9c79b345733b5040934202085ba7ca60573746e8d165b0255667c56b1a19bd25
      - registry.eu-de.bluemix.net/armada-master/haproxy:384f4234ef230049fb646f6fc224c770c513486e
      sizeBytes: 47395302
    - names:
      - registry.ng.bluemix.net/armada-master/configmap-operator-registry@sha256:5ca1f6e54a3d9248461af22d78dc23d10acf7cb2850de7ab186712e1c5fdcf4c
      - registry.ng.bluemix.net/armada-master/configmap-operator-registry:v1.6.1
      sizeBytes: 30845098
    - names:
      - registry.eu-de.bluemix.net/armada-master/armada-calico-extension@sha256:b6e593474781d7079110bc1746f3c9fb5410a247b4920332ddf6556e5d5e690c
      - registry.eu-de.bluemix.net/armada-master/armada-calico-extension:378
      sizeBytes: 28092449
    - names:
      - registry.eu-de.bluemix.net/armada-master/keepalived@sha256:8d945168cbe75f54b2bc0631f9fa4df29a4399ffa66e75ff862588993508bd2a
      - registry.eu-de.bluemix.net/armada-master/keepalived:208
      sizeBytes: 13920347
    - names:
      - registry.eu-de.bluemix.net/armada-master/ingress-auth@sha256:b54625d141b5960b8b2366b661930831915e046735a8041153fc7208618a40d1
      - registry.eu-de.bluemix.net/armada-master/ingress-auth:421
      sizeBytes: 13446451
    - names:
      - registry.eu-de.bluemix.net/armada-master/keepalived-watcher@sha256:69a6963524e8096490e5ddc09ea57cb3128f89a0a4a31167a84be62e262e618c
      - registry.eu-de.bluemix.net/armada-master/keepalived-watcher:208
      sizeBytes: 13042400
    - names:
      - registry.eu-de.bluemix.net/armada-master/alpine@sha256:36c3a913e62f77a82582eb7ce30d255f805c3d1e11d58e1f805e14d33c2bc5a5
      - registry.eu-de.bluemix.net/armada-master/alpine:3.6
      sizeBytes: 2019814
    - names:
      - registry.eu-de.bluemix.net/armada-master/pause@sha256:7b7f8d5850ea3c7285f3053d803d39eb0d47ccec1b74d714b9f6a953c241faba
      - registry.eu-de.bluemix.net/armada-master/pause:3.1
      sizeBytes: 315427
    nodeInfo:
      architecture: amd64
      bootID: 6f1f7199-f239-45b5-b23c-aa3acb57f933
      containerRuntimeVersion: containerd://1.3.4
      kernelVersion: 4.15.0-112-generic
      kubeProxyVersion: v1.17.11+IKS
      kubeletVersion: v1.17.11+IKS
      machineID: aacf6317840c4d9f9dd805444003ac53
      operatingSystem: linux
      osImage: Ubuntu 18.04.5 LTS
      systemUUID: B10A2F81-DF99-C691-3AEA-E2E6D98C8297
- apiVersion: v1
  kind: Node
  metadata:
    annotations:
      node.alpha.kubernetes.io/ttl: "0"
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
    creationTimestamp: "2020-08-19T08:05:18Z"
    labels:
      arch: amd64
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/instance-type: u3c.2x4
      beta.kubernetes.io/os: linux
      failure-domain.beta.kubernetes.io/region: eu-de
      failure-domain.beta.kubernetes.io/zone: fra02
      ibm-cloud.kubernetes.io/external-ip: 158.177.96.102
      ibm-cloud.kubernetes.io/ha-worker: "true"
      ibm-cloud.kubernetes.io/iaas-provider: softlayer
      ibm-cloud.kubernetes.io/internal-ip: 10.194.178.177
      ibm-cloud.kubernetes.io/machine-type: u3c.2x4
      ibm-cloud.kubernetes.io/os: UBUNTU_18_64
      ibm-cloud.kubernetes.io/region: eu-de
      ibm-cloud.kubernetes.io/sgx-enabled: "false"
      ibm-cloud.kubernetes.io/worker-id: kube-bsudhljf0rbvej5nb690-myclusterfr-default-000002fe
      ibm-cloud.kubernetes.io/worker-pool-id: bsudhljf0rbvej5nb690-91c7ee1
      ibm-cloud.kubernetes.io/worker-pool-name: default
      ibm-cloud.kubernetes.io/worker-version: 1.17.11_1537
      ibm-cloud.kubernetes.io/zone: fra02
      kubernetes.io/arch: amd64
      kubernetes.io/hostname: 10.194.178.177
      kubernetes.io/os: linux
      node.kubernetes.io/instance-type: u3c.2x4
      privateVLAN: "2933248"
      publicVLAN: "2933246"
      topology.kubernetes.io/region: eu-de
      topology.kubernetes.io/zone: fra02
    name: 10.194.178.177
    resourceVersion: "7610"
    selfLink: /api/v1/nodes/10.194.178.177
    uid: 9a2be53a-0498-4a5b-9199-19c524bf212c
  spec:
    providerID: ibm://843df9e8c9bd4d37931ad48e7ba87c1f///bsudhljf0rbvej5nb690/kube-bsudhljf0rbvej5nb690-myclusterfr-default-000002fe
  status:
    addresses:
    - address: 10.194.178.177
      type: InternalIP
    - address: 158.177.96.102
      type: ExternalIP
    - address: 10.194.178.177
      type: Hostname
    allocatable:
      cpu: 1920m
      ephemeral-storage: "99894567244"
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      memory: 2923348Ki
      pods: "110"
    capacity:
      cpu: "2"
      ephemeral-storage: 102687672Ki
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      memory: 4033364Ki
      pods: "110"
    conditions:
    - lastHeartbeatTime: "2020-08-19T08:35:50Z"
      lastTransitionTime: "2020-08-19T08:05:18Z"
      message: kubelet has sufficient memory available
      reason: KubeletHasSufficientMemory
      status: "False"
      type: MemoryPressure
    - lastHeartbeatTime: "2020-08-19T08:35:50Z"
      lastTransitionTime: "2020-08-19T08:05:18Z"
      message: kubelet has no disk pressure
      reason: KubeletHasNoDiskPressure
      status: "False"
      type: DiskPressure
    - lastHeartbeatTime: "2020-08-19T08:35:50Z"
      lastTransitionTime: "2020-08-19T08:05:18Z"
      message: kubelet has sufficient PID available
      reason: KubeletHasSufficientPID
      status: "False"
      type: PIDPressure
    - lastHeartbeatTime: "2020-08-19T08:35:50Z"
      lastTransitionTime: "2020-08-19T08:05:38Z"
      message: kubelet is posting ready status. AppArmor enabled
      reason: KubeletReady
      status: "True"
      type: Ready
    daemonEndpoints:
      kubeletEndpoint:
        Port: 10250
    images:
    - names:
      - registry.eu-de.bluemix.net/armada-master/node@sha256:ebf85ef4b604dd7eacfda4525338490872b1ac5ceae5affb0b6f14de34cc34f5
      - registry.eu-de.bluemix.net/armada-master/node:v3.12.2
      sizeBytes: 89710502
    - names:
      - registry.eu-de.bluemix.net/armada-master/cni@sha256:cff126929f3180d4a35662d10b6e5a78aa76011dff851f626beb28a7e8ea7e9e
      - registry.eu-de.bluemix.net/armada-master/cni:v3.12.2
      sizeBytes: 77500843
    - names:
      - registry.eu-de.bluemix.net/armada-master/olm@sha256:6178efe6eaa89154566a9db77a8de798c8cfcd3fc63e76073b1d8e27d1c639de
      - registry.eu-de.bluemix.net/armada-master/olm:0.14.1-IKS-1
      sizeBytes: 75262632
    - names:
      - registry.eu-de.bluemix.net/armada-master/kubernetesui-dashboard@sha256:635b2efff46ac709b77ee699579e171aabc37a86a3e8c2c78153b763edcadcf4
      - registry.eu-de.bluemix.net/armada-master/kubernetesui-dashboard:v2.0.3
      sizeBytes: 67606657
    - names:
      - registry.eu-de.bluemix.net/armada-master/ingress@sha256:edf946bce0cf8cbde06d48341e09afd0afc462822db4d2d0901944bf375553a4
      - registry.eu-de.bluemix.net/armada-master/ingress:647
      sizeBytes: 49406062
    - names:
      - registry.eu-de.bluemix.net/armada-master/haproxy@sha256:9c79b345733b5040934202085ba7ca60573746e8d165b0255667c56b1a19bd25
      - registry.eu-de.bluemix.net/armada-master/haproxy:384f4234ef230049fb646f6fc224c770c513486e
      sizeBytes: 47395302
    - names:
      - registry.eu-de.bluemix.net/armada-master/armada-calico-extension@sha256:b6e593474781d7079110bc1746f3c9fb5410a247b4920332ddf6556e5d5e690c
      - registry.eu-de.bluemix.net/armada-master/armada-calico-extension:378
      sizeBytes: 28092449
    - names:
      - registry.eu-de.bluemix.net/armada-master/storage-file-plugin@sha256:84030ef01271378814412aaf1e7192fdab3a18325989fb891c998835afc4af0e
      - registry.eu-de.bluemix.net/armada-master/storage-file-plugin:377
      sizeBytes: 27945250
    - names:
      - registry.eu-de.bluemix.net/armada-master/kube-controllers@sha256:abb80679b203e6f2b2490d4cc8919dd3de2e0f2719eeda9a4a4c15ddf0068101
      - registry.eu-de.bluemix.net/armada-master/kube-controllers:v3.12.2
      sizeBytes: 23123431
    - names:
      - registry.eu-de.bluemix.net/armada-master/metrics-server@sha256:c0efe772bb9e5c289db6cc4bc2002c268507d0226f2a3815f7213e00261c38e9
      - registry.eu-de.bluemix.net/armada-master/metrics-server:v0.3.7
      sizeBytes: 21031646
    - names:
      - registry.eu-de.bluemix.net/armada-master/kubernetesui-metrics-scraper@sha256:d78f995c07124874c2a2e9b404cffa6bc6233668d63d6c6210574971f3d5914b
      - registry.eu-de.bluemix.net/armada-master/kubernetesui-metrics-scraper:v1.0.4
      sizeBytes: 16018412
    - names:
      - registry.eu-de.bluemix.net/armada-master/cluster-proportional-autoscaler-amd64@sha256:a2db01cfd2ae1a16f0feef274160c659c1ac5aa433e1c514de20e334cb66c674
      - registry.eu-de.bluemix.net/armada-master/cluster-proportional-autoscaler-amd64:1.7.1
      sizeBytes: 14900064
    - names:
      - registry.eu-de.bluemix.net/armada-master/keepalived@sha256:8d945168cbe75f54b2bc0631f9fa4df29a4399ffa66e75ff862588993508bd2a
      - registry.eu-de.bluemix.net/armada-master/keepalived:208
      sizeBytes: 13920347
    - names:
      - registry.eu-de.bluemix.net/armada-master/ingress-auth@sha256:b54625d141b5960b8b2366b661930831915e046735a8041153fc7208618a40d1
      - registry.eu-de.bluemix.net/armada-master/ingress-auth:421
      sizeBytes: 13446451
    - names:
      - registry.eu-de.bluemix.net/armada-master/coredns@sha256:2044ffefe18e2dd3d6781e532119603ee4e8622b6ba38884dc7ab53325435151
      - registry.eu-de.bluemix.net/armada-master/coredns:1.6.9
      sizeBytes: 13401433
    - names:
      - registry.eu-de.bluemix.net/armada-master/keepalived-watcher@sha256:69a6963524e8096490e5ddc09ea57cb3128f89a0a4a31167a84be62e262e618c
      - registry.eu-de.bluemix.net/armada-master/keepalived-watcher:208
      sizeBytes: 13042400
    - names:
      - registry.eu-de.bluemix.net/armada-master/addon-resizer@sha256:35745de3c9a2884d53ad0e81b39f1eed9a7c77f5f909b9e84f9712b37ffb3021
      - registry.eu-de.bluemix.net/armada-master/addon-resizer:1.8.11
      sizeBytes: 9347950
    - names:
      - registry.eu-de.bluemix.net/armada-master/vpn-client@sha256:98209366cd1f86a5c133afccf16876e8d94e29fd066bb55789d452ef93f61d09
      - registry.eu-de.bluemix.net/armada-master/vpn-client:2.4.6-r3-IKS-116
      sizeBytes: 5389684
    - names:
      - registry.eu-de.bluemix.net/armada-master/alpine@sha256:36c3a913e62f77a82582eb7ce30d255f805c3d1e11d58e1f805e14d33c2bc5a5
      - registry.eu-de.bluemix.net/armada-master/alpine:3.6
      sizeBytes: 2019814
    - names:
      - registry.eu-de.bluemix.net/armada-master/pause@sha256:7b7f8d5850ea3c7285f3053d803d39eb0d47ccec1b74d714b9f6a953c241faba
      - registry.eu-de.bluemix.net/armada-master/pause:3.1
      sizeBytes: 315427
    nodeInfo:
      architecture: amd64
      bootID: 11d63f70-d2b4-452f-83f6-523db8320ed2
      containerRuntimeVersion: containerd://1.3.4
      kernelVersion: 4.15.0-112-generic
      kubeProxyVersion: v1.17.11+IKS
      kubeletVersion: v1.17.11+IKS
      machineID: 623f13a56d58406b85cf50108089f06c
      operatingSystem: linux
      osImage: Ubuntu 18.04.5 LTS
      systemUUID: C7488054-F479-7BE9-7E11-D64C80C1C043
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""`
