### ISSUE TITLE
Support command line (and web UI) way of adjusting time period for collecting logs

### ISSUE THREAD

**Issue by markpundsack** [replicatedhq/troubleshoot#277]
Some customers produce so many logs that a support bundle may only contain 3 seconds of logs. A vendor can adjust the size of logs to collect, but with that kind of volume, it's not possible for a vendor to provide a single configuration that will work for all customer scenarios. It would be much better for the enterprise user to be able to narrow down the collection themselves, based on their knowledge of when a problem has occurred. 

I'm not positive about best design here, but can imagine a command line option (and in Kots, a web form) to specify a start and end time, or maybe just a start time and we collect as many logs as the vendor spec specifies. Or maybe they specify a time and we collect +/- around that time.

Related, but probably out of scope, might be to let a user specify a request ID that we could filter for. If they really generate a massive amount of logs, this kind of ID might be necessary to truly collect everything a vendor needs for debugging.

Also related, but probably out of scope, if a vendor includes some kind of advanced logging capabilities (e.g. Elasticsearch, Loki), could we tap into that capability to return aggregated and filtered logs?

**Comment by nathanfishcircleci** [comment]
Greylog is also a great option for log aggregation. We have issues with very large customers bringing down their systems or only getting the last ~3 minutes of logs when trying to run a support bundle. Having some advanced filtering/searching functionality should alleviate this problem.

**Comment by matias-manavella-nimble** [comment]
@markpundsack Using the flag kubectl logs --since-time=2020-10-13T15:41:12Z we can retrieve logs starting from a specific time. We could enhance the specs of the logs collector to accept a day and time, maybe under `limits`. 
Maybe something like:
```yaml
limits:
  #If unspecified defaults to current day and time
  day: 2020-10-13
  time: 15:41:12
  maxLines: 10000
```
I think it wouldn't require lots of changes in the code. Let me know what  you think

**Comment by markpundsack** [comment]
@manavellamnimble Thanks, that seems like a good direction. Only thing is, the end-user should not need to modify the support-bundle configuration spec. Those are provided by the vendor and shouldn't really be viewed, let alone edited by the end user. This needs to be an override the user provides the CLI (or web UI) at collection time.

e.g. `kubectl support-bundle --since-time=2020-10-13T15:41:12Z file_or_url`.

**Comment by markpundsack** [comment]
Even better if we also support `--since=1h` and other variants that `kubectl` supports.

```
      --since=0s: Only return logs newer than a relative duration like 5s, 2m, or 3h. Defaults to all logs. Only one of
since-time / since may be used.
      --since-time='': Only return logs after a specific date (RFC3339). Defaults to all logs. Only one of since-time /
since may be used.
```

Side note, but if someone asks for logs since 1h, and that is too much, we should probably indicate that we've truncated the logs.

**Comment by matias-manavella-nimble** [comment]
@markpundsack okey, I will start working on the flags. There are a couple of flags already created (e.g interactive, format, collect-without-permissions, etc..) but they have no place in the  docs, should we create a new section for these flags (including the new ones we are talking about now)? Of course the related flags would be also described in the logs collector, but it may be useful to have them all together somewhere

**Comment by markpundsack** [comment]
@manavellamnimble We should probably get someone from core engineering to review this design as well. There might be some logs that don't make sense to be affected by `--since` or `--since-time`. I can't think of any, but worth evaluating.

And yes, we should add a doc page somewhere for CLI arguments. It doesn't fit cleanly in any of the existing sections. We may have to create a new one in between Support Bundle and Collect. Maybe called Usage? Alternatively, we could put them as pages at the bottom of Preflight Checks and Support Bundle.

**Comment by matias-manavella-nimble** [comment]
@markpundsack what if the collector is specified in the flag? I don't know if the end-user knows the collectors included and the names, or if the vendor can somehow specify this flags.
`kubectl support-bundle --since-time="collector1-dateAndTime" --since-time="collector2-dateAndTime" file_or_url`

**Comment by markpundsack** [comment]
Possibly, but I think it would be easier if the user didn't need to know that.

**Comment by matias-manavella-nimble** [comment]
@markpundsack and what if the user specifies the selector for a pod (and the container name if necessary)? Then if there is a collector for that pod it is overwritten, and if there is none, a new collector is created...something like: 

`kubectl supportbundle --pod-selector="app=api" --container="nodeapp" --namespace="default" --since-time=2020-10-13T15:41:12Z file_or_url`

If the end-user is the one responsible of doing the overriding and we want it to be applied only to a specific collector, I don't know if there is a lot of other options.

**Comment by markpundsack** [comment]
That looks like a pretty poor UX though. It's kinda cool if we let end users add new pod logs to a support bundle, but it's bad that we make users know details like that. If they're going to do that, they may as well use `kubectl`. I mean, sure, there's the slight benefit that it wraps it up nicely with other information, and one tarball to send to a vendor, but it kills the ease-of-use.

Can we start by thinking what this might apply to? Do the standard collectors include any logs or anything for which `time-since` might apply?

The default collectors are just `clusterInfo` and `clusterResources`, right? Most of those are json outputs about the point in time when the support bundle is collected and don't vary based on time. But `events` looks like an array of events that goes back in time. I don't see a way to limit that report. Is there some internal limit? Like 10,000 events or something? Is there any reason to apply `since` or `since-time` to that event reporting? Probably, but we don't seem to provide it today.

For vendor-supplied collectors, most things are also point-in-time. Run pods is limited to 10,000 lines, but we don't provide a way to specify which 10,000 lines to report, if there's more. So that leaves Pod Logs as a vendor-specified collector. And we do provide a way to specify `maxAge` and `maxLines`. `maxAge` is equivalent to `since`.

Adding CLI arguments to specify which collector to modify would only apply if the vendor has specified multiple pod log collectors. (If there's only one pod log collector, you don't need to specify which one). If the vendor does do that, does it makes sense to let the user specify different `since` times for each pod log? I can imagine some hypothetical weird edge case, but more likely, if there's a problem that happened an hour ago, wouldn't you want all pod logs to look at that same time period? Do vendors really need to see the most recent logs from one pod and hour-old logs from another? Or if one pod has fewer logs, would it be a problem to truncate them at an hour even though we could report them back for weeks?

Or put another way, if we just applied `since` or `since-time` to all pod logs, would there be any downsides? It would certainly be easier. And if there are any downsides, can we mitigate them in some other way? Like could we only apply it to logs that exceed the maxLines count? Or should we require vendors to identify which pod log collectors to parametrize in this way? Or maybe even literally have them write templatable or parameterizable configuration like `maxAge: ${SINCE:720h}` but probably more like Replicated template format. I'd rather not require them to plan ahead for this, but if it's a problem, we could possibly do that.

My gut is that the first iteration should just allow someone to specify `--since` on the command line, and we apply it to all pod logs as an override to the `maxAge` parameter.

**Comment by matias-manavella-nimble** [comment]
@markpundsack Great, thank you for the answer, it is super clear. I will start working on this and send a PR, and then we can discuss further
