### ISSUE TITLE
Error: run collectors: support-bundle failure on windows 10

### ISSUE THREAD

**Issue by TomerAdmon** [replicatedhq/troubleshoot#282]
Steps to reproduce:
1. Using Windows 10 machine client install support-bundle and execute the following command:  `kubectl support-bundle https://troubleshoot.run/HK948JL2g`

Result: 
Error message
> C:\Users\tomer.a>kubectl support-bundle https://troubleshoot.run/HK948JL2g
> Error: run collectors: find file name: check file exists: CreateFile support-bundle-2020-10-12T14:30:52.tar.gz: The filename, directory name, or volume label syntax is incorrect.
> exit status 1

The same command with the same cluster on a Ubuntu machine works

OS: Windows 10 (10.0.18363 N/A Build 18363)
Kubectl version: 1.19.0

**Comment by matias-manavella-nimble** [comment]
@salahalsaleh Hi! I thinks this  issue was related to your PR https://github.com/replicatedhq/troubleshoot/pull/284 , as windows does not accepts ":" in the filenames. Can you close this issue?
