### ISSUE TITLE
Logs collectors should not spin infinitely

### ISSUE THREAD

**Issue by laverya** [replicatedhq/troubleshoot#306]
log collectors should take a finite amount of time - say up to 1m by default - before exiting.

**Comment by xavpaice** [comment]
Function `Logs()` uses `ctx := context.Background()` as the context for log collection.  This should be reconsidered, maybe use `WithTimeout` instead, maybe like the docs example:

```
const timeout = 60
ctx, cancel := context.WithTimeout(context.Background(), timeout)
defer cancel()
```

**Comment by drohnow** [comment]
In absence of a go test; I have create a video to show how I tested the context timeout.

https://replicated.zoom.us/rec/share/OmbJglomqirmDdi_OW9h4NaTs5FdxNDxy0SrTI_A1Bzv8SnZKWkw026eSmcV_KDE.bw6loRj6SqU6oxhy?startTime=1671059574000
Passcode: f2YY3=D2
