### ISSUE TITLE
kubectl preflight hangs when a bad URL is passed in spec.uploadResultsTo

### ISSUE THREAD

**Issue by MrBenJ** [replicatedhq/troubleshoot#38]
Reproduce by putting a bad URL in spec, then run `kubectl preflight my_bad_yaml_file.yaml`

```yaml
spec:
  uploadResultsTo: httpzsd://bad.url.lol
```

**Comment by matias-manavella-nimble** [comment]
@laverya I think this issue was already solve in your commit of december, 2019 https://github.com/replicatedhq/troubleshoot/commit/55f2ed44bfec43efb981830b2e29c7d9ad7c378d, can you close this issue?

**Comment by emosbaugh** [comment]
closing
