### ISSUE TITLE
Add the functionality of using host collectors in support-bundle

### ISSUE THREAD

**Issue by limkaisean** [replicatedhq/troubleshoot#399]
From what I can see, the host collectors only work for host preflight. I think that it would be great if the host collectors can be used in generating the support bundle as well. For example, it would be nice and useful to collect the disk usage in a support bundle.

**Comment by diamonwiggins** [comment]
Hello @limkaisean . We've made progress on this recently with https://github.com/replicatedhq/troubleshoot/pull/574. Still work to do here as Host Analyzers haven't been added yet, but will keep you posted as the work comes along.

**Comment by diamonwiggins** [comment]
This was added in `v0.40.0` of troubleshoot https://troubleshoot.sh/docs/host-collect-analyze/overview/ 😄 . Going to close this one out.
