### ISSUE TITLE
It should be possible to run troubleshoot with no redactors

### ISSUE THREAD

**Issue by laverya** [replicatedhq/troubleshoot#448]
**Describe the rationale for the suggested feature.**

Sometimes a bundle may be destined only for internal use, or there may be concerns that useful data was removed by redactors. As such, there should be a way to collect a bundle without redactions.

**Describe the feature**

Add a CLI flag or environment variable that when set will prevent redactors from being run. It may also be a good idea to change the bundle filename in these scenarios to ensure that unredacted bundles are not inadventently treated as already sanitized.

**Describe alternatives you've considered**

**Additional context**

Collect currently hardcodes this: https://github.com/replicatedhq/troubleshoot/blob/050f5939c6f4e90f7b3aea102ad96c261deb7be9/pkg/supportbundle/collect.go#L34

But https://github.com/replicatedhq/troubleshoot/blob/050f5939c6f4e90f7b3aea102ad96c261deb7be9/pkg/collect/collector.go#L262-L265 does respect it

**Comment by xavpaice** [comment]
The current version has a `--redact` flag to disable this.
