### ISSUE TITLE
Flag --redact doesn't work

### ISSUE THREAD

**Issue by floridoo** [replicatedhq/troubleshoot#452]
**Bug Description**

The CLI flag [--redact](https://github.com/replicatedhq/troubleshoot/blob/master/cmd/troubleshoot/cli/root.go#L40) doesn't work.

**Expected Behavior**

When setting `--redact=false`, the default redactions should be disabled (according to --help output)

**Steps To Reproduce**

Run `support_bundle` with `--redact=false`. The default redactors are still executed.

**Additional Context**

Include the following information.
- Troubleshoot version: v0.15.0
- Operating system: any
- Operating system version: any

Would you be willing to accept a pull request to implement the missing functionality?

**Comment by mhrabovcin** [comment]
Fixed by https://github.com/replicatedhq/troubleshoot/pull/406
