### ISSUE TITLE
support  expanding directories when running a local path

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/troubleshoot#51]
`kubectl support-bundle ~/test.yaml`

Get /Users/username/test.yaml: unsupported protocol scheme ""

**Comment by markpundsack** [comment]
@marccampbell What does this mean?

**Comment by marccampbell** [comment]
At the time of creating this, we didn't support that command. You couldn't use a `~` in the positional argument. I just verified and this is no longer an issue, it appears to be supported.  Closing.
