### ISSUE TITLE
Allow the secret collector to be able to gather a complete map of all the keys and values

### ISSUE THREAD

**Issue by tillt** [replicatedhq/troubleshoot#535]
**Describe the rationale for the suggested feature.**

As a developer for debugging my application stack's spin-up phase after the fact - ie CI runs, I have come into situations where adequate logging was not available but the state and contents of some of my secrets would give me some intel. Given that my environment is purely non production, as a developer I am keen on as much information as I can get. The secret collector does support including a value per secret when a key is given but only then. In my scenario I may not know which secrets I am interested in, in advance.

**Describe the feature**

For my purpose it would be great if the secret collector was able to return a complete map of all the keys and values there are within that secret. This feature could be marked as for development and non production environments only given the underlying security risks. 

**Describe alternatives you've considered**

Use something outside of troubleshoot.sh - some `kubectl` and shell glue wrapped in a container.

**Additional context**

The `SecretOutput` type as defined in pkg/collect/secret.go would need to allow for something like 
```
	Data         map[string]string `json:"data,omitempty"`
```

This is purely for illustrating my problem, not for pre-determining a result.

**Comment by xavpaice** [comment]
Including unredacted data in a support bundle, that was stored in cluster as a secret, is a very risky process.  I would want to avoid any form of wildcard, knowing that it's very likely redactors would miss items, and folks would trip over that losing their customer's trust.
