### ISSUE TITLE
Copy collector does not apply redactions

### ISSUE THREAD

**Issue by divolgin** [replicatedhq/troubleshoot#58]

**Comment by marccampbell** [comment]
bumping to 1.6.0

**Comment by matias-manavella-nimble** [comment]
@divolgin @marccampbell Hi Dimitriy, Marc, since the last update, the redactor opens the tar file collected by the copy collector (and every tar file inside) and apply the redactors to every file, should this be closed?

**Comment by banjoh** [comment]
I believe this can be closed. Will do so unless there are objections @divolgin
