### ISSUE TITLE
Create proposal for streamlined log collection

### ISSUE THREAD

**Issue by chris-sanders** [replicatedhq/troubleshoot#672]
**Describe the rationale for the suggested feature.**

Log collection has grown organically and is need of a review for UX. The collection and analysis of logs while possible is confusing. Here are some examples I'm aware of directly.

1. The `logs` collector, as documented, only collects logs from running pods. If a pod fails to start, even if some containers start and others don't the collector produces nothing. This means an analyzer for the logs collector can only identify issues for healthy containers which is fairly limiting.
2. The `logs` collector stores logs, as all collectors, in a collector specific folder based on the name of the collector. Because of item 1 above this folder may or may not appear in a support bundle depending if it was able to run. This adds to confusion as logs seem to 'sometimes' be present.
3. The `cluster-resources` collector only collects logs from pods that fail to start. This collector therefore has information on failed logs but doesn't have information pods that are running, that requires the above `logs` collector.
4. The `sbctl` tool only knows about `cluster-resources` collector so the only logs you can ever find with it are logs for pods that are unhealthy.
5. Other collectors like the `ceph` collector (which is actually a Rook collector) also store logs which are unknown to sbctl and it is unclear from documentation how it behaves with regards to healthy or unhealthy pods.

**Describe the feature**

Fixing this requires a big picture review of the UX and interactions between various collectors and the `sbctl` tool. I won't attempt to design the solution in this issue but instead request that a design document be developed and discussion had to determine the solution. Goals for this design then should include:

1. Ensure all logs that are collected are accessible to `sbctl`
2. Improve usability for users who desire to review logs for pods in all stages of health. This need not necessarily require sweeping changes to collectors if it's determined there is a well thought out process to do this if documenting that process solves the issue. Although I have my doubts that is the case.
3. Ensure the final solution keeps Analyzers as DRY (don't repeat yourself) as possible. A user shouldn't have to write 2 or 3 analyzer specs to check for different lifecycles if the same check can reasonably apply to all lifecycles.

**Describe alternatives you've considered**

There are architecture changes such as [this design proposal](design/proposal-standard-interface.md) which in implementing make enough changes to address this issue entirely as well. It may be that the solution is to prioritize other improvements which will by their nature fix this and several other issues as well.

**Comment by xavpaice** [comment]
I'm going to revisit the design proposal and split it into two:

* simple logging alterations, so that the goal here is met
* take the more complex refactor of log collection and concurrent collections to it's own, separate, proposal which likely has a different priority and different discussion/decision points.

**Comment by xavpaice** [comment]
Logs:

* #744 
* #745 

I have updated the proposal here to revise things, it's not so much a logs proposal as a propsal for improving the concurrency of the project and centralizing the pod log collection.
