### ISSUE TITLE
Add support to CLI to search for all secrets that contain Troubleshoot specs

### ISSUE THREAD

**Issue by xavpaice** [replicatedhq/troubleshoot#699]
## Request

Ref design #663.

Currently we can specify a secret with the URI for a Troubleshoot spec.  With #683 we add the ability to list multiple specs on the CLI, but not a wildcard, directory, or search pattern.

This request is to implement a search function whereby any secrets that can be found with a matching label (default to  `troubleshoot.io/kind=supportbundle-spec`), will be collected and used as if they had been specified on the CLI.  This search should be made in the namespace defined in the same way as the kubectl client.

## In scope

* add a switch to the CLI, which triggers Troubleshoot to search for secrets
  * in the namespace specified with `-n` or `--namespace`, or the current context for the Kubernetes client
  * all namespaces if `-A` or `--all-namespaces` is provided
  * for any secret with the label `troubleshoot.io/kind=supportbundle-spec` unless the `-l` switch is provided to override that
* Include each secret found as if it had been specified on the CLI (i.e. use them all)
* Test coverage
* Documentation

## Out of scope

* KOTS changes to make use of this addition

## NOTE

The package `"k8s.io/cli-runtime/pkg/genericclioptions"` may be helpful with the kubectl options, see [this example](https://github.com/kubernetes/sample-cli-plugin).

This task may be affected by work on #694, which uses the URI specified in a spec only on the specs provided on the CLI.  To be clear, the specs found in secrets with this task need to be considered as specs provided on the CLI, therefore the URI will need to be read and used.

Also: Note that KOTS uses the `kots.io/kind=supportbundle`label [here](https://github.com/replicatedhq/kots/blob/main/pkg/store/kotsstore/supportbundle_store.go#L239) to describe collected support bundles.

Kots does store a Troubleshoot spec, with the name `kotsadm-$APPSLUG-supportbundle`, however it does not currently have a label which can be used to identify it.

## Definition of done

- [x] CLI switch enabling Troubleshoot to search for and use all secrets with a label `troubleshoot.io/kind=supportbundle-spec` (default), or a CLI specified label
- [x] CLI supports kubectl's `-l, --selector=''` switch to override the label searched for
- [x] CLI supports kubectl's `-A`, `--all-namespaces`, `-n`, `--namespace` switches to override namespace
- [x] Unit tests for the new implementation
- [ ] Documentation updated to show usage of this new feature in https://troubleshoot.sh/docs

**Comment by emosbaugh** [comment]
> By using the same label that is used when the KOTS application adds a supportbundle secret, we allow folks to use Troubleshoot from the CLI with the same specs as if they run from the KOTS application.

it looks like this is actually a [support bundle](https://github.com/replicatedhq/kots/blob/main/pkg/store/kotsstore/supportbundle_store.go#L239) not a support bundle spec

> add a switch to the CLI, which triggers Troubleshoot to search for secrets in the namespace specified, or the default namespace for the k8s client used, for any secret with the label supportbundle.

i like this idea. if kots were to store specs in a secret, should we allow the end user to specify the label and use `-l, --selector=''`? for example i may want to generate a bundle for a [specific app](https://github.com/replicatedhq/kots/blob/main/pkg/store/kotsstore/supportbundle_store.go#L239).

```
kubectl supportbundle -l troubleshoot.io/kind=supportbundle-spec -l kots.io/appid=2E8MgZlONGe5Wmc6BGctnxwVobj
```

I would consider namespacing the label. somthing like `troubleshoot.io/kind=supportbundle-spec` or `kots.io/kind=supportbundle-spec` if we choose to use kots.io as we do today.

**Comment by chris-sanders** [comment]
The only additional comment I have, is that while `kubectl` defaults to the 'default' namespace I'd suggest we default to all namespaces if not explicitly restricted. The reason I suggest this is users not familiar with K8s who are collecting a support bundle are likely to collect nothing by accident. An experienced user on the other hand will likely _always_ have to type `-A` for all of their collections as it seems you usually want to collect everything b/c you don't yet know what isn't working. If we always ask people to provide the flag, I think making it the default is reasonable even if it differs from `kubectl`

**Comment by xavpaice** [comment]
Updated the description based on this discussion.  The tradeoff with defaulting to all namespaces is that for clusters where the person running Troubleshoot doesn't have access to all namespaces (e.g. existing cluster), we will see the `support-bundle` command have different defaults to the `kubectl` command which is confusing. I think we should require the `-A` to search all namespaces, so that the behavior is consistent between `kubectl` and `support-bundle`.  This is also consistent with the collectors in Troubleshoot, e.g. [logs](https://troubleshoot.sh/docs/collect/logs/#namespace-optional).

**Comment by xavpaice** [comment]
You can read the Troubleshoot spec stored by kots with this: `kubectl get secret kotsadm-xavdemo-supportbundle -o jsonpath='{.data.support-bundle-spec}' |base64 -d`.

Secrets that contain bundle specs should therefore look like this example in order to be consistent with the ones already stored, with labels adjusted etc.:

```
apiVersion: v1
data:
  support-bundle-spec: (base64 encoded support bundle spec)
kind: Secret
metadata:
  creationTimestamp: "2022-09-05T02:25:36Z"
  labels:
    kots.io/backup: velero
    kots.io/kotsadm: "true"
  name: kotsadm-xavdemo-supportbundle
  namespace: default
  resourceVersion: "7390"
  uid: 54b629cf-7d3a-4a08-992a-753028b430d3
type: Opaque
```

Example spec:

```
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  annotations:
    kots.io/exclude: "true"
  creationTimestamp: null
  name: example-support-bundle
spec:
  analyzers:
(etc....)
```

**Comment by diamonwiggins** [comment]
> Updated the description based on this discussion. The tradeoff with defaulting to all namespaces is that for clusters where the person running Troubleshoot doesn't have access to all namespaces (e.g. existing cluster), we will see the support-bundle command have different defaults to the kubectl command which is confusing. I think we should require the -A to search all namespaces, so that the behavior is consistent between kubectl and support-bundle. This is also consistent with the collectors in Troubleshoot, e.g. [logs](https://troubleshoot.sh/docs/collect/logs/#namespace-optional).

In general, I'd agree here if we were starting from scratch, but one thing to note is that there is already a `namespace` CLI flag that determines which namespace we'll collect from and today it doesn't default to `default`, so essentially everything is collected. Are we suggesting that we change this behavior? 

And somewhat related, do we agree that we can share the existing namespace flag for both this new secrets search functionality as well as requests that are made during collection? I think it's a fair bet to say yes, but worth getting others opinions.

**Comment by diamonwiggins** [comment]
@xavpaice I've opened a PR. I don't have any tests at the moment, but figured i'd let you get some eyes on it so that I have your feedback for tomorrow.

> all namespaces if -A or --all-namespaces is provided

Besides this item, I believe all requirements are being met outside of any testing/docs. As I mentioned in my earlier comment, default behavior in Troubleshoot today is to collect everything if `-n` isn't specified, so we'll need to decide if we'd like to change that.

**Comment by xavpaice** [comment]
This looks to be going in the right direction.  Note that #683 is merged now if that affects anything here.

> In general, I'd agree here if we were starting from scratch, but one thing to note is that there is already a `namespace` CLI flag that determines which namespace we'll collect from and today it doesn't default to `default`, so essentially everything is collected. Are we suggesting that we change this behavior?

Re namespaces, I missed that Troubleshoot already has this default behavior, seeing that some of the collectors themselves do not.  I would prefer that we do not change any defaults with this change, when I requested to require -A to search all namespaces that was to try to keep things consistent with current behavior.  In other words, let's redefine this task to match the existing behavior of the `namespace` CLI flag.

Regards sharing that flag - yes, let's share it.  I see no value in separating it out.

**Comment by xavpaice** [comment]
Re-opened to add some docs in https://troubleshoot.sh (last task in the list)

**Comment by xavpaice** [comment]
Closing - the CLI help text is adequate, and we need to have a full CLI doc in the troubleshoot.sh site which is outside of the scope of this task.
