### ISSUE TITLE
Add support to run redactors on an existing support bundle

### ISSUE THREAD

**Issue by banjoh** [replicatedhq/troubleshoot#705]
**Describe the rationale for the suggested feature.**

If a support bundle with sensitive information is generated, it would be beneficial if there was a way to redact this information from the support bundle after the fact. At the moment a redactor can be added and another support bundle recreated, but there may be cases where a cluster may have mutated leading to losing helpful troubleshooting data such as logs (think log rotation).

**Describe the feature**

With a support bundle at hand, I would envision two ways of recreating the support bundle.
- In the application manager UI, add a way to reprocess an existing support bundle (run the redactors and analysers only) _(this is out of scope of troubleshoot because its part of KOTS, but adding here to describe a possible use case)_.
- On the CLI, run something akin to the following. Passing in a support bundle implies not to run collectors.
```
kubectl support-bundle ./support-bundle-with-new-redactor.yaml --support-bundle.tar.gz
```

**Comment by xavpaice** [comment]
This could follow the same pattern as implemented for Analyzers: 

```
 ./bin/support-bundle analyze  --help
Analyze a support bundle using the Analyzer definitions provided

Usage:
  support-bundle analyze [url] [flags]

Flags:
      --bundle string   filename of the support bundle to analyze
  -h, --help            help for analyze
      --output string   output format: json, yaml
      --quiet           enable/disable error messaging and only show parseable output
```

**Comment by xavpaice** [comment]
Added triaged label, this is a very handy feature for folks writing redactors
