### ISSUE TITLE
Example collector and analyzer spec using URI for updates

### ISSUE THREAD

**Issue by xavpaice** [replicatedhq/troubleshoot#712]
## Request

The work in #694 adds the ability and documentation for a URI field to be used for updating specs.

This request is to create an example of that usage, exercising the feature.  Suggested is a collector and analyzer that searches for the ekco version, and warns if it's out of date or if it there's a known error with the version installed (e.g. lack of certificate rotation).

## In scope

* Add one yaml file to the https://github.com/replicatedhq/troubleshoot-specs/ repo which contains the appropriate collector and analyzer for ecko versions, plus a uri pointing to the doc in Github
* The yaml itself must contain enough detail that it can run standalone without needing to go to the URI.

## Definition of done

- [x] New spec is written and merged to https://github.com/replicatedhq/troubleshoot-specs/
- [x] A post on https://community.replicated.com/ explaining how this can be used from the CLI, and referencing the docs created in #694

**Comment by adamancini** [comment]
@xavpaice https://github.com/replicatedhq/replicated-docs/pull/832
https://github.com/replicatedhq/troubleshoot-specs/blob/main/in-cluster/ekco.yaml
