### ISSUE TITLE
Troubleshoot docs should have a CLI reference

### ISSUE THREAD

**Issue by adamancini** [replicatedhq/troubleshoot#749]
**Describe the rationale for the suggested feature.**

With the addition of some new flags, I think it's time we should document the CLI interfaces to Troubleshoot

**Describe the feature**

Probably a new top-level node on [troubleshoot.sh](https://github.com/replicatedhq/troubleshoot.sh) for the CLI and subpages for each, should at least describe the syntax and any long flags supported.

**Comment by xavpaice** [comment]
https://app.shortcut.com/replicated/story/58732/troubleshoot-sh-docs-for-cli-usage created for the docs team.

**Comment by xavpaice** [comment]
Preflight is documented [here](https://troubleshoot.sh/docs/preflight/cli-usage/).

Support-bundle is documented [here](https://docs.replicated.com/enterprise/troubleshooting-an-app#generating-a-bundle-using-the-cli)
