### ISSUE TITLE
termui is not actively maintained

### ISSUE THREAD

**Issue by banjoh** [replicatedhq/troubleshoot#789]
**Description**

[Termui](https://github.com/gizak/termui) is the upstream project troubleshoot uses to render the terminal UI when using the cli to generate support bundles. Its active maintenance was questioned [here](https://github.com/gizak/termui/issues/304) a year ago which seems not to have a positive response

We either need to maintain our [folk](https://github.com/replicatedhq/termui) or consider an alternative. The upstream project has many open PRs and Issues pending.

**Candidates (if replacing this dependency)**
- https://github.com/charmbracelet/bubbletea
- https://docs.pterm.sh/

**Comment by xavpaice** [comment]
Likely resolved as part of replacing the CLI tools with a new CLI (#933)

**Comment by banjoh** [comment]
I found another library that may be of interest

https://docs.pterm.sh/

**Comment by xavpaice** [comment]
The developer is back.  Though the project doesn't see a lot of love, we're not affected by any known issues and so swapping out the entire UI for something else doesn't appear to be as urgent as it might have been.
