### ISSUE TITLE
Preflights that have `uploadResultsTo` should not be interactive

### ISSUE THREAD

**Issue by xavpaice** [replicatedhq/troubleshoot#792]
## Description

When using the Admin Console and preflights can't complete because of permissions, and Admin Console gives the user instructions for running the command from the console, it's supposed to upload the results to the admin console and then exit. Instead, it enters interactive mode and shows the preflight results in the CLI leaving the end-user confused. Do they need to save and quit? What if they don't save?

I'm not positive the CLI is even sending the report at all, but if it is, it should certainly not go into interactive mode.

I'm pretty sure we used to just send the results to the admin console, and the admin console responded immediately. If it is being sent, then there's a separate bug in the admin console that it's not handling it in realtime, leaving the end-user confused.

For support bundles, I know that the bundle **is** being sent to the admin console since I can see it in the list. But I'm still confused whether I need to save first or not before quitting. But it's less clear that the support bundle shouldn't go into interactive mode because maybe the user **wants** to debug via the CLI. 

## Impact

* Replicated impact:
* Vendor impact:
* End-user impact:

## Environment

kots 1.87.2
Replicated Preflight 0.44.0

**Comment by xavpaice** [comment]
From https://app.shortcut.com/replicated/story/60510/preflights-that-have-uploadresultsto-should-not-be-interactive.

@markpundsack can you confirm the CLI command being used (or, requested by the Admin Console to use)?

**Comment by chris-sanders** [comment]
Possibly @ajp-io might be able to help with this as well?

**Comment by markpundsack** [comment]
@xavpaice The command is just:
```
kubectl preflight secret/$APP/${APP}-preflight
```

**Comment by markpundsack** [comment]
Note that one possible solution is to have the admin console add `--interactive=falase` to the command to use, but I personally believe that should be implied if `uploadResultsTo` is in the spec.
