### ISSUE TITLE
troubleshoot should be able to show interactive results on a bundle that's already been collected

### ISSUE THREAD

**Issue by adamancini** [replicatedhq/troubleshoot#794]
**Describe the rationale for the suggested feature.**

After the analysis stage, an interactive terminal UI is presented to display the results of the analysis.  It might be nice to be able to show this screen post-collection if you already have a support bundle.

It kind of seems like `kubectl support-bundle analyze` is set up to do that, but it requires that you pass in an analyzer spec and a support bundle file - not quite clear on the intent for how this would be used, except maybe to run new/additional analyzers that were not in the original spec?  

But in any case, if the analyzer results file is in the .tar.gz archive, we should be able to simply present the results to the user.

**Describe the feature**

Perhaps something like `kubectl support-bundle view-results` that will look for `analysis.json` in a support bundle archive and jump straight to the interactive results TUI.

**Comment by xavpaice** [comment]
This should be rolled into the new CLI, design in #934

**Comment by xavpaice** [comment]
closing as #933 will handle this requirement
