### ISSUE TITLE
Provide container images on release

### ISSUE THREAD

**Issue by chris-sanders** [replicatedhq/troubleshoot#808]
**Describe the rationale for the suggested feature.**

While building release it wouldn't be a lot of extra effort to build and host minimal images on ghcr alongside the binary releasees. This provides an additional option and makes consuming Troubleshoot to make checks in-cluster a lot easier. For example if you wanted to use Helm Hooks to check before upgrading your application.

**Describe the feature**

Build images for each of the projects binaries on release so that they can be run in-cluster if desired without a user having to create and maintain their own troubleshoot images.

**Comment by xavpaice** [comment]
https://github.com/replicatedhq/troubleshoot/blob/main/deploy/Dockerfile.troubleshoot has the current Dockerfile used to make the Docker images released with each tag.  These need testing.

**Comment by xavpaice** [comment]
Tested the image on Dockerhub, it works fine and is updated.
