### ISSUE TITLE
Abstract support-bundle file locations from collectors

### ISSUE THREAD

**Issue by danj-replicated** [replicatedhq/troubleshoot#812]
**Describe the rationale for the suggested feature.**

Currently the support bundle structure is dictated by where people hardcode files in their collectors, but this is hard to discover when writing analyzers.

**Describe the feature**

It would be nice if the definitions for file locations for collectors were centralised somewhere in troubleshoot so we can reference them from both collectors and analyzers.

**Additional context**

This requires some discussion as it could affect how sbctl interacts with support bundles.

**Comment by diamonwiggins** [comment]
Can you provide a before and after example of a collector and what the directory structure would look like in a bundle? Curious if you're suggesting that we no longer use `name/collectorName` fields for how the collected files are potentially named, or that we just provide a clearer directory structure for each collector.

**Comment by danj-replicated** [comment]
hmm, I don't think I want to change the bundle structure itself, just where it's defined. 

so for example, instead of saying `output.SaveResult(c.BundlePath, "cluster-resources/namespaces.json", bytes.NewBuffer(namespaces))` we can, for example (not definitive don't quote me on this) set the resource paths in the collector type definition.

so if I wanted to retrieve namespace data from this collector in an analyzer, I could ask for `ClusterResourcescollector.paths.namespaces`

**Comment by danj-replicated** [comment]
with https://github.com/replicatedhq/troubleshoot/pull/780 merged, one half of this (reading resources without having explicity specify the file to read from) has become a reality. 

however for a "proper" implimentation of this I'd like to see the full structure of the `cluster-resources` collector output defined in code so we can move away from per collector-function hardcoded paths.

**Comment by xavpaice** [comment]
Moving this work to "long term" in the roadmap, since the final half of the task is not clearly defined, and not in progress.
