### ISSUE TITLE
RFE: meaningful default name to save the preflights checks 

### ISSUE THREAD

**Issue by camilamacedo86** [replicatedhq/troubleshoot#825]
**Describe the rationale for the suggested feature.**

After run `kubectl preflight https://preflight.replicated.com` and choose the s option to save the default output seems to be "o". Could we change that for for example preflight_checks.txt or  preflight_checks_<timestamp>.txt? 

![Screenshot 2022-11-07 at 10 39 23](https://user-images.githubusercontent.com/7708031/200290997-393d2920-bb3c-427a-848c-a91a8e69b3c0.png)

**Comment by chris-sanders** [comment]
lol, I think "o" is a pretty strange default surly we can do better than that.

**Comment by xavpaice** [comment]
This appears to be the same for support-bundle - however in preflight, the help for the flag is in `./pkg/preflight/flags.go`, and in support-bundle it's in `./cmd/troubleshoot/cli/root.go`.  I don't see at first look where the default is set for preflight.

Definition of done:

- [ ] if `-o` is specified for either preflight or support-bundle, without supplying a filename, the output filename should be named preflight.tar.gz or support-bundle.tar.gz
- [ ] if you run preflight or support-bundle interactively and opt to save the file, the output filename should be named preflight.tar.gz or support-bundle.tar.gz

**Comment by DexterYan** [comment]
By looking at two previous PRs #769 and #538, seems the default logic was:

- [ ] if -o is not specified for preflight, the output filename should be named 
`
<preflight name>-results-<date>.txt
`
- [ ] if -o is specified for preflight, without supplying a filename, there will be an error which is
`
Error: flag needs an argument: 'o' in -o
`
- [ ] if -o is specified for preflight, with supplying a filename, the output filename should be the same as cli input

And for `kubectl preflight https://preflight.replicated.com`, the default output file name will be `example-results-2022-11-14T14_54_14.txt`

For the current issue, it is possible that we are not using the `flags.StringVarP` function to migrate the previous `cmd.Flags().StringP("output", "o", "", "***")`. I will make a pr for that.
