### ISSUE TITLE
rename example domains to avoid misleading and make them more intuitive

### ISSUE THREAD

**Issue by camilamacedo86** [replicatedhq/troubleshoot#844]
**Describe the rationale for the suggested feature.**

The link https://preflight.replicated.com returns an example to be used with preflights.
And then, the link https://support-bundle.replicated.com  returns an example to be used with bundles.

The idea here would only rename it for something like `https://preflight-example.replicated.com` and `https://support-bundle-example.replicated.com` in order to avoid scenarios like:

- a) Users trying out the replicated solutions might think that they can test out them with `kubectl preflight https://preflight.replicated.com` and does not get that it is just an example and is not a valid check
- b) It might bring confusion among contributors for not think that is just an example and believe that it might be used in some project under the org.

**Alternative Solution**

Add on the info on the readme: https://github.com/replicatedhq/troubleshoot/pull/845/files

**Describe the feature**

Rename the link domain to make more clear that is only an example

**Comment by chris-sanders** [comment]
What's the use case for having a dedicated subdomain that points to an example of a spec? If it's an example presumably just having it in the repository is sufficient. I can't think of a reason to serve a single example from a subdomain.

I propose we either:
1. Move the bundles found at the original subdomains to point to actually maintained preflight (kurl) and support bundles (kots) files so they are production default bundles that the teams want available at a simple domain.
2. Remove the subdomains entirely if the products aren't using them I see no nee to serve up an example spec at the subdomain.

**Comment by chris-sanders** [comment]
Given that we've found kURL is indeed not using these URLs and the documentation has been updated to clarify the use I'm going to close this issue as 'won't fix'. The only remaining task would be to include "sample" or "example" in the subdomain and I don't think it's reasonable for a user to assume a subdomain's usage based only on it's name.
