### ISSUE TITLE
rook analyzer: should look for host port 9090 to be open

### ISSUE THREAD

**Issue by adamancini** [replicatedhq/troubleshoot#849]
**Describe the rationale for the suggested feature.**

Rook-Ceph `csi-rbdplugin` uses hostPort 9090 for communication, which can be blocked by some host-level services such as RH Cockpit.

`cockpit.socket` configuration in some RedHat systems is listening on :9090 for port activation of `cockpit.service`

This open socket will result in `csi-rbdplugin` pods in CrashLoopBackOff and we should see a corresponding message in pod logs about being unable to bind to `<host-ip>:9090`

**Describe the feature**

Detect if that socket is occupied and suggest disabling services that might be occupying that port.  Other OS level services could be Symantec EPM, Prometheus, McAfee Web Gateway.

**Comment by xavpaice** [comment]
Many thanks for raising this!

This check is included in the kURL preflight for Ceph from version 1.9.12 onwards.

Unless there's a specific ask for the Troubleshoot code itself I will close out this issue now as fixed.
