### ISSUE TITLE
Update GH workflow actions to newer versions

### ISSUE THREAD

**Issue by banjoh** [replicatedhq/troubleshoot#850]
**Describe the rationale for the suggested change.**

As part of keeping the project healthy, we need to keep up with newer versions of GH actions in our [workflows](https://github.com/replicatedhq/troubleshoot/tree/main/.github/workflows) which may have various improvements or bug fixes.

Here is a non-exhaustive like of some of our current GH actions and their latest major versions
- actions/setup-go@v1 -> actions/setup-go@v3
- actions/checkout@v2 -> actions/checkout@v3
- actions/upload-artifact@v1 -> actions/upload-artifact@v3
- actions/download-artifact@v1 -> actions/download-artifact@v3
- goreleaser/goreleaser-action@v2 -> goreleaser/goreleaser-action@v3

**Describe alternatives you've considered**

Depend on old versions

**Comment by camilamacedo86** [comment]
Hi @banjoh, 

Just to confirm are we speaking about update the deps in the workflows, Am I right? 

See that the project has https://github.com/replicatedhq/troubleshoot/blob/main/.github/dependabot.yml , however, it seems not configured to looking for to update the workflows as well. If so, we might could sort it out with, i.e:

https://github.com/kubernetes-sigs/kubebuilder/blob/89f58d3f43ff0f9e8c22c9ffff2f6fc3a744248b/.github/dependabot.yml#L9-L19

I pushed a PR : https://github.com/replicatedhq/troubleshoot/pull/851

**Comment by banjoh** [comment]
> Hi @banjoh,
> 
> Just to confirm are we speaking about update the deps in the workflows, Am I right?
> 
> See that the project has https://github.com/replicatedhq/troubleshoot/blob/main/.github/dependabot.yml , however, it seems not configured to looking for to update the workflows as well. If so, we might could sort it out with, i.e:
> 
> https://github.com/kubernetes-sigs/kubebuilder/blob/89f58d3f43ff0f9e8c22c9ffff2f6fc3a744248b/.github/dependabot.yml#L9-L19
> 
> I pushed a PR : #851

I meant GH actions in https://github.com/replicatedhq/troubleshoot/tree/main/.github/workflows. I'll update the description with example actions

**Comment by camilamacedo86** [comment]
Hi @banjoh, 
 
> I meant GH actions in https://github.com/replicatedhq/troubleshoot/tree/main/.github/workflows. I'll update the description with example actions

So, all fine. The pr https://github.com/replicatedhq/troubleshoot/pull/851 should fix this one.
