### ISSUE TITLE
Filter Custom Resource objects for better analysis 

### ISSUE THREAD

**Issue by spron-in** [replicatedhq/troubleshoot#863]
**Describe the rationale for the suggested feature.**

It is useful for support teams gather information only about specific Custom Resource, not all of them. At the same time show the user the results of Analyzers only for this specific Custom Resource. 
Also parsing a yaml file that has multiple Custom Resource objects with yamlCompare does not work at all, as you are not sure which CR you are checking.

**Describe the feature**

The idea would be to have a filter for Custom Resource in the Collector definition, that would allow to either set a namespace and a name of the CR (or a regexp).

**Describe alternatives you've considered**

yamlCompare can only partially solve the problem

**Additional context**

None.

**Comment by xavpaice** [comment]
Thank you for raising this.  We will need to add it to the roadmap, though if you wished to make a change we'd be happy to ensure it's reviewed in a timely manner.
