### ISSUE TITLE
Misguiding documentation

### ISSUE THREAD

**Issue by ricardomaraschini** [replicatedhq/troubleshoot#869]
**Bug Description**

There is a section in the documentation that states ["A list of all available collectors"](https://troubleshoot.sh/docs/collect/all/) but in fact it does not list all available collectors:

<img width="288" alt="Screenshot 2022-11-22 at 10 03 54" src="https://user-images.githubusercontent.com/1385436/203271693-17f3988f-cfb1-4663-a3b4-2e068abcc26d.png">
<img width="384" alt="Screenshot 2022-11-22 at 10 04 09" src="https://user-images.githubusercontent.com/1385436/203271751-be61b02b-1422-455a-bec3-fa4d3e90f3c1.png">

Collectors related to hosts are not listed. That drove me to believe that a feature (a collector for [host or system packages](https://github.com/replicatedhq/troubleshoot/pull/857)) was not present.

**Expected Behavior**

The list shows up all collectors or at least have a link to the host collectors.

**Comment by xavpaice** [comment]
I suspect this is more about making sure the difference between collectors and [host collectors](https://troubleshoot.sh/docs/host-collect-analyze/overview/) is clear, and folks are guided to the right place?

**Comment by ricardomaraschini** [comment]
Yes, that is correct.

**Comment by chris-sanders** [comment]
I think we could just update the "All Collectors" page to list all collectors and differentiate between HostCollectors and Collectors. Then someone reading the docs, jumping directly to the "All Collectors" page truly gets an overview of everything they can currently collect.
