### ISSUE TITLE
Max size of pod logs

### ISSUE THREAD

**Issue by xavpaice** [replicatedhq/troubleshoot#878]
**Internal Tracking**: [#55381](https://app.shortcut.com/replicated/story/55381)

### Problem to solve
Setting a max size limit on the pod logs. This is to ensure that the support bundle is not too large, the existing limit of max age or max lines would not necessarily help with this as there could be lines which are extremely long and thus increase the bundle size.

### Impact
This could result in large support bundles which would be harder to obtain from customers. Also this was possible in both Ship and native schedulers so should exist to keep feature parity 

### Proposed Solution
Add `limits.maxSize` or `limits.maxBytes` field to the pod logs parameters

**Comment by xavpaice** [comment]
Changes to make:

* `troubleshootv1beta2.LogLimits` needs a new parameter for a size limit
* add `LimitBytes` to logs.go in func `setLogLimits()`, suggest to add a default value of TBD.  This is where we could set the `LimitBytes` value supplied to the Kubernetes API based on a value supplied to Troubleshoot in a different format (or not).

We could consider the use of either bytes (`limits.maxBytes`) which matches the `LimitBytes` defined in the Kubernetes API code, or we could utilize some conversion so that we provide `LimitBytes` based on an input in the format nnK, nnM, nnG, etc.

The `clusterResources` collector sets a limit for logs it collects to 500 lines.  We should consider making this configurable in the collector, and using the `setLogLimits()` function from the logs collector.

Definition of done:

- [x] the logs collector for Troubleshoot accepts a maximum size option
- [x] the `clusterResources` collector has a maximum size limit for logs, either with a default value or an optional configuration value.
- [ ] the change is documented
- [ ] tests are written for all code that was changed

**Comment by edgarlanting** [comment]
Rewrote and cleaned up the PR for Troubleshoot as well as opening a Troubleshoot docs PR to address this change.

**Comment by xavpaice** [comment]
Reopened to track the docs PR
