### ISSUE TITLE
hostCollector: `copy` to copy files/folders from a host filesystem to the support bundle

### ISSUE THREAD

**Issue by adamancini** [replicatedhq/troubleshoot#881]
**Describe the rationale for the suggested feature.**

Right now we have `copyFromHost` that runs as an in-cluster collector, which works great if pods can be scheduled, but in some cases of a node-down or cluster-down problem, it might be nice to be able to have a "simple" way to collect a specific file/path/glob-pattern from the host.

**Describe the feature**

A native Golang collector that can take a Go path that will copy the desired files into a destination folder in the support bundle.  Be able to report errors like "file not found" so a user has a little more information on the failure mode, and authors can trigger outcomes based on those conditions.  It should also preserve the original file mode and ownership information so we don't inadvertently change one of those things, which might be germane to a problem.

**Describe alternatives you've considered**

Right now my solution is to use `run` to execute some shell commands to get the output I want, which works but could fail for lots of reasons, since it relies on host dependencies.

**Additional context**

see https://github.com/adamancini/troubleshoot-specs/blob/cni/host/cni-conf.yaml#L12

**Comment by edgarlanting** [comment]
Short note to update that I'm working on a draft PR while I test a few different options on Go's native way to copy files.

**Comment by edgarlanting** [comment]
Thanks for this description for the need of an 'alternative' `copyFromHost` solution Ada!

What I'm currently looking to use is something like `io.Copy` to get this done.
