### ISSUE TITLE
Recognize distribution type Kind

### ISSUE THREAD

**Issue by mnp** [replicatedhq/troubleshoot#892]
**Describe the rationale for the suggested feature.**

The analyzer should recognize Kind cluster type and report a new `Distribution` identifier.

**Describe the feature**

Kind it's an official SIG, Replicated/Helm work fine on it, and it has uses in dev, CI and test at least. We are considering customer use cases also. See 
* https://kind.sigs.k8s.io/
* https://github.com/kubernetes-sigs/kind 

**Describe alternatives you've considered**

`{{repl Distribution}}` turns up "" on Kind. We can sometimes hack around this.

**Additional context**

Thanks for reading.

**Comment by xavpaice** [comment]
Thanks for raising this!

The next step is to spin up a test Kind cluster and have a look to see how it's identified.  The Distribution identifier in Troubleshoot has a few different things it checks, because different types of cluster have different ways to identify themselves.

Is this something you envisage seeing in development environments only, or in production usage?

**Comment by mnp** [comment]
Low-ish prio for us. We are just using Kind for dev and CI at the moment (happy to share our GH action goop), but we are thinking there might eventually be a customer use here for small/edge prod environments.  It's lazy/convenient since it runs inside a container so the host requirements are mostly moot.

Yeah I had a look at `analyze/distribution.go` to see what could be keyed off. There is no dumptruck of labels as some other distros provide (cough) but there are some images  running: grep the describe-node.json attachment for `kindest`.  Another difference that jumps out is the default SC is `rancher.io/local-path` but that might be a red herring overlapping with actual Rancher.

I've also attached a stock support bundle.

[describe-node.tar.gz](https://github.com/replicatedhq/troubleshoot/files/10185787/describe-node.tar.gz)

[support-bundle-2022-12-08T08_27_24.tar.gz](https://github.com/replicatedhq/troubleshoot/files/10185788/support-bundle-2022-12-08T08_27_24.tar.gz)
