### ISSUE TITLE
Detect EKS Anywhere distribution

### ISSUE THREAD

**Issue by xavpaice** [replicatedhq/troubleshoot#897]
Internal Tracking: [#63025](https://app.shortcut.com/replicated/story/63025)

Problem to solve
Currently, the distribution analyzer is not able to recognize i.e. vSphere that can be used as a deployment target for EKS Anywhere. An empty string is returned in this case.

The issue also applies to Distribution() function used in KOTS (as both things use the same code under the hood).

https://anywhere.eks.amazonaws.com/

Impact
Providing an accurate distribution will help with analyzing issues that our customers may have.

Proposed Solution

**Comment by AmberAlston** [comment]
The story associated with this request has been archived in the Replicated ticketing system due to issue age and lack of activity. If you do not believe this issue should be archived, please respond with information on why you believe this request is still valuable/needed.

/publish-internal
