### ISSUE TITLE
Kubectl preflight --output=file doesn't send output to file

### ISSUE THREAD

**Issue by z4ce** [replicatedhq/troubleshoot#906]
**Bug Description**
running `kubectl preflight --format=json --interactive=false --output=/tmp/output` does not result in the file /tmp/output being created with the output.

**Expected Behavior**

`/tmp/output` has the output from the preflight run

**Steps To Reproduce**
run:
`kubectl preflight --format=json --interactive=false --output=/tmp/output` 
notice /tmp/output is not created

**Additional Context**
```
kubectl preflight version
Replicated Preflight 0.49.1
```
MacOS Ventura

**Comment by xavpaice** [comment]
verified, using the command below and v0.51.1

```
kubectl preflight --format=json --interactive=false --output=/tmp/output https://raw.githubusercontent.com/replicatedhq/troubleshoot/main/config/samples/troubleshoot_v1beta2_preflight.yaml
```

**Comment by CpuID** [comment]
https://github.com/replicatedhq/troubleshoot/pull/951 fixes this 👍 

test coverage to ensure no future regressions for it are in https://github.com/replicatedhq/troubleshoot/pull/949 also
