### ISSUE TITLE
Log Collector (pkg/collect/logs.go) -- Do not try and collect logs from pods/containers that do not exist.

### ISSUE THREAD

**Issue by drohnow** [replicatedhq/troubleshoot#917]
Please review video; code attempts to collect pod logs even when a pod does not exist within the cluster.

https://replicated.zoom.us/rec/share/OmbJglomqirmDdi_OW9h4NaTs5FdxNDxy0SrTI_A1Bzv8SnZKWkw026eSmcV_KDE.bw6loRj6SqU6oxhy?startTime=1671059574000
Passcode: f2YY3=D2

Request: if a pod does not exist, then skip log collection.

**Comment by xavpaice** [comment]
it would be helpful if possible to summarize the video here, with what needs to happen to reproduce the issue, what the behaviour is now, and what we expect it to be.

Most of the collectors generate a list of pods to collect from a search, so the circumstances where the pod is no longer there between being specified and collected should be minimal, but we should at least fail quickly and cleanly if a pod's logs are not able to be collected for any reason.

Would we expect to see an error in a log/directory for failed collections?

**Comment by xavpaice** [comment]
Fixed in #932
