### ISSUE TITLE
Routinely run go vuln on our codebase

### ISSUE THREAD

**Issue by banjoh** [replicatedhq/troubleshoot#944]
**Describe the rationale for the suggested feature.**

I addition to GH's vulnerability tools, it would be beneficial to routinely run [go vuln](https://go.dev/security/vuln/) tool which also checks vulnerabilities from other additional databases. When it comes to vulnerability monitoring, the more databases we check our codebase against the better.

**Describe the feature**

- Run `govulncheck` on each PR
- Run `govulncheck` routinely against upstream `main` and report findings.

**Describe alternatives you've considered**

Leave things as they are and depend on GH advisories, which are already quite good.

**Additional context**

I ran it on my machine and it took 11 seconds. I assume each run should average around that, with upper limits of 20s.

**Comment by xavpaice** [comment]
I've asked the Replicated security folks to have a look at this issue.

**Comment by tcalotta** [comment]
What is the overlap between govuln and dependabot? At least from a high level, they seem to perform the same role.

**Comment by banjoh** [comment]
@tcalotta main difference I see here is reports being pulled from Go vulnerability database. I can't tell how much more information this will offer though.

The other bit I find good to have is having the capability to run `go vuln` locally, say before committing code.

**Comment by tcalotta** [comment]
I don't have a problem including govuln in the pipeline. I would advise you stick with a single scanner and make sure it's always applied in the same way (i.e. if you've ignored unfixed vulns then make sure everyone does that) so you have repeatable results. Using multiple scanners can lead you down a rabbit hole chasing ghosts.

Our other public repos typically use trivy but if you feel strongly that govuln offers further benefit, that's fine with me.

**Comment by St0rmz1** [comment]
Unless there is a specific reason or benefit to use go vuln, I'd prefer to stick with using trivy so we have consistency.

**Comment by banjoh** [comment]
> Unless there is a specific reason or benefit to use go vuln, I'd prefer to stick with using trivy so we have consistency.

Being consistent is a fair argument. I'll shelve using `go vuln` in favour of `trivy` which we have working in troubleshoot already.
