### ISSUE TITLE
Support bundle spec to check cluster down has failures always

### ISSUE THREAD

**Issue by camilamacedo86** [replicatedhq/troubleshoot#967]
**Bug Description**

No matter the install that I do with kURL when I follow up https://community.replicated.com/t/kurl-how-can-i-generate-a-support-bundle-when-my-kubernetes-cluster-is-down/911 I will always see the following failures and warnings. Therefore, that seems a problem with the spec and not with kURL install. 

<img width="1312" alt="Screenshot 2023-01-18 at 10 00 57" src="https://user-images.githubusercontent.com/7708031/213142025-b9bc17ba-3b38-4bca-b29a-5a709a5d9be2.png">

<img width="1367" alt="Screenshot 2023-01-18 at 10 01 06" src="https://user-images.githubusercontent.com/7708031/213142060-212de3f8-1645-43ce-a67b-0593b3df33a8.png">

**Expected Behavior**

- Install `curl https://kurl.sh/latest | sudo bash` in an environment with all pre-requirements 
- Then, follow the steps:  https://community.replicated.com/t/kurl-how-can-i-generate-a-support-bundle-when-my-kubernetes-cluster-is-down/911 

```
curl -L https://github.com/replicatedhq/troubleshoot/releases/latest/download/support-bundle_linux_amd64.tar.gz | tar xzvf -
./support-bundle https://raw.githubusercontent.com/replicatedhq/troubleshoot-specs/main/host/cluster-down.yaml
```
 
And check all green. 

**Steps To Reproduce**

Create an ubuntu VM (i.e gcreate ubuntu-2204-lts ubuntu-2204-lts-myinstance) and run the following commands:

```
curl https://kurl.sh/latest | sudo bash
curl -L https://github.com/replicatedhq/troubleshoot/releases/latest/download/support-bundle_linux_amd64.tar.gz | tar xzvf -
./support-bundle https://raw.githubusercontent.com/replicatedhq/troubleshoot-specs/main/host/cluster-down.yaml
```

**Additional Context**

Not all requirements shows be in place after the kURL install see:

<img width="1416" alt="Screenshot 2023-01-18 at 10 07 43" src="https://user-images.githubusercontent.com/7708031/213144205-e0ad6b17-5df3-487e-b3c7-bbbe30ab0f59.png">

**Comment by danj-replicated** [comment]
@camilamacedo86 can you try running the cluster-down support bundle as root / with sudo as recommended in the linked community post?

**Comment by camilamacedo86** [comment]
OH. Good point @danj-replicated,

That sort out the errors, but not the warnings for etcd:
 
<img width="760" alt="Screenshot 2023-01-18 at 10 28 29" src="https://user-images.githubusercontent.com/7708031/213148206-68eeb509-7bbe-4984-bf8f-09318c7285e7.png">

Why do we do those checks? What are their purpose?

**Comment by camilamacedo86** [comment]
The problem here is with the spec. Therefore, this issue was moved to: https://github.com/replicatedhq/troubleshoot-specs/issues/34

Closing this one.
